use std::time::Duration;

/// the webview piece inspired by Wormhole project on https://codepen.io/wodniack/pen/XJbYWXx and
/// modified by ai also other parts are generated by ai and modified by me to work with lumin_wallpaper_rs
use lumin_wallpaper_rs::{EventForwarder, WindowsPlatform};
use tao::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    platform::windows::WindowExtWindows,
    window::WindowBuilder,
};

use wry::WebViewBuilder;

/// Prints the complete hierarchy rooted at `hwnd`.
///
/// Includes:
/// - Parent chain
/// - Root information
/// - All direct children
/// - All descendants recursively

fn main() -> Result<(), Box<dyn std::error::Error>> {
    std::fs::write("./index.html", html())?;

    let mut html_dir = std::env::current_dir()?.into_os_string();
    html_dir.push("/index.html");

    let event_loop = EventLoop::new();

    let window = WindowBuilder::new()
        .with_title("Black Hole")
        .with_inner_size(tao::dpi::LogicalSize::new(1000.0, 700.0))
        .build(&event_loop)?;

    let _webview = WebViewBuilder::new()
        .with_url(format!("file://{}", html_dir.to_string_lossy()))
        .build(&window)?;

    // this part attaches it to desktop
    let hwnd = window.hwnd();
    println!("{:x}", hwnd);
    let a = EventForwarder::new(hwnd, true, true, false);
    let _ = a.unwrap().forward_events();

    let a = WindowsPlatform::auto_attach(hwnd, false).unwrap();
    a.start_watcher(Duration::from_millis(100)).unwrap();

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => {
                *control_flow = ControlFlow::Exit;
            }

            _ => {}
        }
    });
}

fn html() -> &'static str {
    r#"<style>
  :root {
    --ui-cyan: #00f0ff;
    --ui-pink: #ff2a85;
    --ui-violet: #a855f7;
    --ui-amber: #ffe56b;
    --ui-ink: rgba(3, 2, 12, 0.78);
    --ui-soft: rgba(226, 232, 240, 0.68);
  }

  body {
    margin: 0;
    padding: 0;
    overflow: hidden;
    background: #020005;
    font-family: Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    color: #e2e8f0;
    user-select: none;
  }

  #canvas-container {
    position: absolute;
    inset: 0;
    width: 100vw;
    height: 100vh;
    z-index: 1;
  }

  #loader {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 20;
    font-size: 12px;
    color: var(--ui-cyan);
    text-shadow: 0 0 18px rgba(0, 240, 255, 0.9);
    letter-spacing: 4px;
    pointer-events: none;
    transition: opacity 0.8s ease;
    white-space: nowrap;
  }

  #micro-ui {
    position: absolute;
    top: 18px;
    right: 18px;
    width: 228px;
    z-index: 10;
    padding: 12px 13px;
    border-radius: 19px;
    overflow: hidden;
    isolation: isolate;
    background:
      radial-gradient(circle at 8% 0%, rgba(0, 240, 255, 0.18), transparent 34%),
      radial-gradient(circle at 95% 18%, rgba(255, 42, 133, 0.18), transparent 36%),
      radial-gradient(circle at 50% 120%, rgba(168, 85, 247, 0.16), transparent 42%),
      linear-gradient(145deg, rgba(10, 7, 24, 0.76), rgba(2, 1, 9, 0.58));
    backdrop-filter: blur(22px) saturate(165%);
    -webkit-backdrop-filter: blur(22px) saturate(165%);
    box-shadow:
      0 20px 58px rgba(0, 0, 0, 0.72),
      0 0 28px rgba(0, 240, 255, 0.08),
      inset 0 1px 0 rgba(255, 255, 255, 0.09),
      inset 0 -18px 40px rgba(0, 0, 0, 0.26);
    max-height: 350px;
    transition:
      max-height 0.42s cubic-bezier(0.25, 1, 0.5, 1),
      padding 0.32s ease,
      transform 0.32s ease,
      box-shadow 0.32s ease;
  }

  #micro-ui::before {
    content: "";
    position: absolute;
    inset: 1px;
    z-index: 0;
    border-radius: 18px;
    background:
      linear-gradient(180deg, rgba(255, 255, 255, 0.075), transparent 30%),
      repeating-linear-gradient(
        90deg,
        rgba(255, 255, 255, 0.026) 0 1px,
        transparent 1px 18px
      );
    opacity: 0.55;
    pointer-events: none;
  }

  #micro-ui::after {
    content: "";
    position: absolute;
    inset: 1px;
    z-index: 1;
    border-radius: 18px;
    border: 1px solid rgba(0, 240, 255, 0.18);
    box-shadow:
      inset 0 0 18px rgba(0, 240, 255, 0.055),
      inset 0 0 26px rgba(255, 42, 133, 0.035);
    pointer-events: none;
  }

  .ui-border {
    position: absolute;
    z-index: 4;
    pointer-events: none;
    opacity: 0.98;
    filter:
      drop-shadow(0 0 7px rgba(0, 240, 255, 0.74))
      drop-shadow(0 0 10px rgba(255, 42, 133, 0.32));
  }

  .ui-border-top,
  .ui-border-bottom {
    left: 15px;
    right: 15px;
    height: 2px;
    background:
      repeating-linear-gradient(
        135deg,
        transparent 0 8px,
        rgba(0, 240, 255, 0.95) 8px 15px,
        rgba(255, 42, 133, 0.92) 15px 21px,
        transparent 21px 32px
      );
    background-size: 64px 2px;
    animation: borderFlowX 2.8s linear infinite;
  }

  .ui-border-top { top: 0; }
  .ui-border-bottom {
    bottom: 0;
    animation-direction: reverse;
  }

  .ui-border-left,
  .ui-border-right {
    top: 15px;
    bottom: 15px;
    width: 2px;
    background:
      repeating-linear-gradient(
        45deg,
        transparent 0 8px,
        rgba(255, 42, 133, 0.9) 8px 15px,
        rgba(0, 240, 255, 0.95) 15px 21px,
        transparent 21px 32px
      );
    background-size: 2px 64px;
    animation: borderFlowY 2.8s linear infinite;
  }

  .ui-border-left { left: 0; animation-direction: reverse; }
  .ui-border-right { right: 0; }

  @keyframes borderFlowX {
    from { background-position: 0 0; }
    to { background-position: 64px 0; }
  }

  @keyframes borderFlowY {
    from { background-position: 0 0; }
    to { background-position: 0 64px; }
  }

  #micro-ui.minimized {
    max-height: 39px;
    padding: 6px 13px;
    box-shadow:
      0 14px 38px rgba(0, 0, 0, 0.68),
      0 0 22px rgba(0, 240, 255, 0.10),
      inset 0 1px 0 rgba(255, 255, 255, 0.08);
  }

  #ui-header {
    position: relative;
    z-index: 5;
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 10px;
    margin-bottom: 10px;
    transition: margin 0.34s ease;
  }

  #micro-ui.minimized #ui-header {
    margin-bottom: 0;
  }

  .title-wrap {
    display: flex;
    align-items: center;
    gap: 9px;
    min-width: 0;
  }

  .title-orb {
    width: 10px;
    height: 10px;
    flex: 0 0 auto;
    border-radius: 50%;
    background:
      radial-gradient(circle, #ffffff 0 18%, var(--ui-cyan) 22% 48%, rgba(255, 42, 133, 0.55) 54%, transparent 74%);
    box-shadow:
      0 0 11px rgba(0, 240, 255, 0.9),
      0 0 20px rgba(255, 42, 133, 0.42);
    animation: corePulse 1.9s ease-in-out infinite;
  }

  @keyframes corePulse {
    0%, 100% { transform: scale(0.92); opacity: 0.78; }
    50% { transform: scale(1.16); opacity: 1; }
  }

  #ui-header h1 {
    display: flex;
    flex-direction: column;
    gap: 1px;
    margin: 0;
    min-width: 0;
    line-height: 1;
  }

  .title-kicker {
    font-size: 8px;
    letter-spacing: 1.75px;
    color: rgba(196, 181, 253, 0.78);
    text-transform: uppercase;
    font-weight: 750;
  }

  .title-main {
    margin-top: 3px;
    font-size: 12px;
    letter-spacing: 1.25px;
    color: #f8fbff;
    text-transform: uppercase;
    font-weight: 850;
    text-shadow:
      0 0 12px rgba(0, 240, 255, 0.62),
      0 0 18px rgba(255, 42, 133, 0.26);
    white-space: nowrap;
  }

  #ui-toggle {
    position: relative;
    width: 27px;
    height: 27px;
    flex: 0 0 auto;
    display: grid;
    place-items: center;
    border-radius: 50%;
    border: 1px solid rgba(0, 240, 255, 0.36);
    background:
      radial-gradient(circle at 50% 25%, rgba(255, 255, 255, 0.18), transparent 30%),
      linear-gradient(145deg, rgba(0, 240, 255, 0.13), rgba(255, 42, 133, 0.10));
    color: #ffffff;
    cursor: pointer;
    font-size: 18px;
    line-height: 1;
    padding: 0 0 2px;
    box-shadow:
      0 0 14px rgba(0, 240, 255, 0.16),
      inset 0 0 12px rgba(255, 255, 255, 0.06);
    transition: transform 0.2s ease, box-shadow 0.2s ease, border-color 0.2s ease;
  }

  #ui-toggle:hover {
    transform: translateY(-1px) scale(1.04);
    border-color: rgba(255, 42, 133, 0.62);
    box-shadow:
      0 0 18px rgba(0, 240, 255, 0.42),
      0 0 18px rgba(255, 42, 133, 0.22),
      inset 0 0 12px rgba(255, 255, 255, 0.08);
  }

  #ui-content {
    position: relative;
    z-index: 5;
    opacity: 1;
    transform: translateY(0);
    transition: opacity 0.26s ease, transform 0.34s ease, visibility 0.34s ease;
  }

  #micro-ui.minimized #ui-content {
    opacity: 0;
    transform: translateY(-8px);
    visibility: hidden;
    pointer-events: none;
  }

  .micro-status {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 5px;
    margin-bottom: 10px;
  }

  .micro-status span {
    height: 19px;
    display: grid;
    place-items: center;
    border-radius: 999px;
    font-size: 8px;
    font-weight: 800;
    letter-spacing: 0.82px;
    color: rgba(234, 246, 255, 0.82);
    text-transform: uppercase;
    background:
      linear-gradient(135deg, rgba(0, 240, 255, 0.12), rgba(255, 42, 133, 0.08));
    border: 1px solid rgba(255, 255, 255, 0.07);
    box-shadow: inset 0 0 12px rgba(0, 240, 255, 0.035);
  }

  .control-group {
    margin-bottom: 9px;
    display: flex;
    flex-direction: column;
    gap: 5px;
  }

  .control-group label {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 8px;
    font-size: 9px;
    color: rgba(226, 232, 240, 0.76);
    text-transform: uppercase;
    font-weight: 800;
    letter-spacing: 0.68px;
  }

  .value-pill {
    min-width: 37px;
    padding: 3px 6px 3px;
    border-radius: 999px;
    color: #ffffff;
    text-align: right;
    font-size: 9px;
    letter-spacing: 0.35px;
    background: rgba(0, 0, 0, 0.32);
    border: 1px solid rgba(0, 240, 255, 0.18);
    box-shadow:
      inset 0 0 10px rgba(0, 240, 255, 0.055),
      0 0 9px rgba(255, 42, 133, 0.055);
  }

  .slider-shell {
    position: relative;
    height: 16px;
    display: flex;
    align-items: center;
  }

  .slider-shell::before {
    content: "";
    position: absolute;
    left: 6px;
    right: 6px;
    top: 50%;
    height: 12px;
    transform: translateY(-50%);
    border-radius: 999px;
    background:
      linear-gradient(90deg, rgba(0, 240, 255, 0.16), rgba(255, 42, 133, 0.12)),
      repeating-linear-gradient(90deg, rgba(255,255,255,0.055) 0 1px, transparent 1px 18px);
    opacity: 0.8;
    pointer-events: none;
  }

  input[type=range] {
    --fill: 50%;
    position: relative;
    z-index: 2;
    -webkit-appearance: none;
    appearance: none;
    width: 100%;
    height: 8px;
    margin: 0;
    border-radius: 999px;
    cursor: pointer;
    outline: none;
    background:
      linear-gradient(
        90deg,
        rgba(0, 240, 255, 0.95) 0%,
        rgba(168, 85, 247, 0.92) calc(var(--fill) * 0.72),
        rgba(255, 42, 133, 0.92) var(--fill),
        rgba(255, 255, 255, 0.075) var(--fill),
        rgba(255, 255, 255, 0.045) 100%
      );
    border: 1px solid rgba(255, 255, 255, 0.085);
    box-shadow:
      inset 0 0 9px rgba(0, 0, 0, 0.82),
      0 0 10px rgba(0, 240, 255, 0.12);
  }

  input[type=range]::-webkit-slider-runnable-track {
    height: 8px;
    border-radius: 999px;
    background: transparent;
  }

  input[type=range]::-webkit-slider-thumb {
    -webkit-appearance: none;
    appearance: none;
    width: 15px;
    height: 15px;
    margin-top: -4px;
    border-radius: 50%;
    border: 1px solid rgba(255, 255, 255, 0.9);
    background:
      radial-gradient(circle at 35% 32%, #ffffff 0 12%, var(--ui-cyan) 18% 45%, var(--ui-pink) 75%);
    box-shadow:
      0 0 0 4px rgba(0, 240, 255, 0.09),
      0 0 14px rgba(0, 240, 255, 0.86),
      0 0 18px rgba(255, 42, 133, 0.42);
    transition: transform 0.16s ease, box-shadow 0.16s ease;
  }

  input[type=range]:hover::-webkit-slider-thumb {
    transform: scale(1.14);
    box-shadow:
      0 0 0 5px rgba(255, 42, 133, 0.12),
      0 0 18px rgba(0, 240, 255, 0.95),
      0 0 22px rgba(255, 42, 133, 0.58);
  }

  input[type=range]::-moz-range-track {
    height: 8px;
    border-radius: 999px;
    background: transparent;
  }

  input[type=range]::-moz-range-thumb {
    width: 15px;
    height: 15px;
    border-radius: 50%;
    border: 1px solid rgba(255, 255, 255, 0.9);
    background: var(--ui-cyan);
    box-shadow:
      0 0 14px rgba(0, 240, 255, 0.86),
      0 0 18px rgba(255, 42, 133, 0.42);
  }

  .hint {
    margin-top: 8px;
    padding: 8px 8px 7px;
    border-radius: 12px;
    text-align: center;
    font-size: 9px;
    line-height: 1.45;
    letter-spacing: 0.55px;
    color: rgba(226, 232, 240, 0.62);
    background:
      linear-gradient(135deg, rgba(0, 240, 255, 0.06), rgba(255, 42, 133, 0.04)),
      rgba(0, 0, 0, 0.24);
    border: 1px solid rgba(255, 255, 255, 0.065);
    box-shadow: inset 0 0 18px rgba(0, 0, 0, 0.22);
  }

  .hint strong {
    color: rgba(255, 255, 255, 0.84);
    font-weight: 850;
  }

  @media (max-width: 768px) {
    #micro-ui {
      top: 14px;
      right: 14px;
      transform: scale(0.9);
      transform-origin: top right;
    }
  }
</style>

<script type="importmap">
{
  "imports": {
    "three": "https://cdn.jsdelivr.net/npm/three@0.174.0/build/three.module.js",
    "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.174.0/examples/jsm/"
  }
}
</script>

<div id="loader">LOADING NEON CORE...</div>
<div id="canvas-container"></div>

<div id="micro-ui">
  <span class="ui-border ui-border-top"></span>
  <span class="ui-border ui-border-right"></span>
  <span class="ui-border ui-border-bottom"></span>
  <span class="ui-border ui-border-left"></span>

  <div id="ui-header">
    <div class="title-wrap">
      <span class="title-orb"></span>
      <h1>
        <span class="title-kicker">Neon Hover</span>
        <span class="title-main">Village Core</span>
      </h1>
    </div>
    <button id="ui-toggle" aria-label="Toggle interface">−</button>
  </div>

  <div id="ui-content">
    <div class="micro-status">
      <span>GPU</span>
      <span>Live</span>
    </div>

    <div class="control-group">
      <label for="rate"><span>Time Flow</span><span id="val-rate" class="value-pill">1.60</span></label>
      <div class="slider-shell">
        <input type="range" id="rate" min="0" max="3" step="0.1" value="1.6" />
      </div>
    </div>

    <div class="control-group">
      <label for="neon"><span>Neon Power</span><span id="val-neon" class="value-pill">1.20</span></label>
      <div class="slider-shell">
        <input type="range" id="neon" min="0.4" max="2.5" step="0.1" value="1.2" />
      </div>
    </div>

    <div class="control-group">
      <label for="fog"><span>Atmosphere</span><span id="val-fog" class="value-pill">1.00</span></label>
      <div class="slider-shell">
        <input type="range" id="fog" min="0" max="2.2" step="0.1" value="1.0" />
      </div>
    </div>

    <div class="control-group">
      <label for="bloom"><span>Bloom Filter</span><span id="val-bloom" class="value-pill">0.10</span></label>
      <div class="slider-shell">
        <input type="range" id="bloom" min="0" max="1.0" step="0.01" value="0.10" />
      </div>
    </div>

    <div class="control-group" style="margin-bottom:6px;">
      <label for="drift"><span>Cam Drift</span><span id="val-drift" class="value-pill">0.25</span></label>
      <div class="slider-shell">
        <input type="range" id="drift" min="0" max="1.5" step="0.05" value="0.25" />
      </div>
    </div>

    <div class="hint"><strong>DRAG</strong> Orbit • <strong>SCROLL</strong> Zoom<br>Instanced village shader console</div>
  </div>
</div>

<script type="module">
  import * as THREE from 'three';
  import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
  import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
  import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
  import { ShaderPass } from 'three/addons/postprocessing/ShaderPass.js';
  import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
  import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
  import { Line2 } from 'three/addons/lines/Line2.js';
  import { LineMaterial } from 'three/addons/lines/LineMaterial.js';
  import { LineGeometry } from 'three/addons/lines/LineGeometry.js';
  import { LineSegments2 } from 'three/addons/lines/LineSegments2.js';
  import { LineSegmentsGeometry } from 'three/addons/lines/LineSegmentsGeometry.js';

  const state = {
    rate: 1.6,
    neon: 1.2,
    fog: 1.0, 
    bloom: 0.10,
    drift: 0.25
  };

  let scene, camera, renderer, composer, bloomPass, screenPass, controls, clock;
  let terrainMaterial, roadMaterial, moonMaterial, lanternMaterial, flameMaterial, churchGlassMaterial;
  let instancedHutMaterial, instancedFoliageMaterial, hologramMaterial;
  let solidBuildingMaterial, solidFoliageMaterial, solidRockMaterial;

  const lineMaterials = [];
  const neonMaterials = [];
  const flameMaterials = [];

  const dynamicObjects = {
    drones: [],
    particles: null,
    windmills: [],
    billboardLights: [],
    billboardPanels: [],
    roadDashes: [],
    clockHands: [],
    instancedHuts: [],
    instancedFoliage: null,
    dragons: []
  };

  const villageGroup = new THREE.Group();
  const lampLights = [];
  const lampGlowSprites = [];
  const moonDirection = new THREE.Vector3(-0.55, 0.75, -0.36).normalize();

  const landmarks = {
    church: { z: -25.0, x: 0, radius: 14.0 },
    clockTower: { z: 20.0, x: 0, radius: 11.0 },
    billboard: { z: -18.0, x: 0, radius: 15.0 }
  };

  function roadCurveX(z) {
    return Math.sin(z * 0.085) * 3.2 + Math.sin(z * 0.18 + 1.4) * 1.25;
  }

  function roadDerivative(z) {
    return Math.cos(z * 0.085) * 0.272 + Math.cos(z * 0.18 + 1.4) * 0.225;
  }

  function terrainHeight(x, z) {
    const broad =
      Math.sin(x * 0.11) * 0.45 +
      Math.cos(z * 0.08) * 0.35 +
      Math.sin((x + z) * 0.05) * 0.2;

    const roadFlatten = Math.exp(-Math.pow((x - roadCurveX(z)) / 4.8, 2.0)) * 0.5;
    return broad - roadFlatten;
  }

  function makeRandom(seed = 123) {
    let s = seed >>> 0;
    return function () {
      s = (s * 1664525 + 1013904223) >>> 0;
      return s / 4294967296;
    };
  }

  function createGlowTexture(size = 256, mode = "cyan") {
    const canvas = document.createElement('canvas');
    canvas.width = size;
    canvas.height = size;
    const ctx = canvas.getContext('2d');
    const g = ctx.createRadialGradient(size * 0.5, size * 0.5, 0, size * 0.5, size * 0.5, size * 0.5);

    if (mode === "fire") {
      g.addColorStop(0.0, 'rgba(255,255,255,1.0)');
      g.addColorStop(0.12, 'rgba(255,218,95,0.95)');
      g.addColorStop(0.36, 'rgba(255,88,26,0.62)');
      g.addColorStop(0.72, 'rgba(255,42,133,0.25)');
      g.addColorStop(1.0, 'rgba(0,0,0,0.0)');
    } else {
      g.addColorStop(0.0, 'rgba(255,255,255,1.0)');
      g.addColorStop(0.15, 'rgba(0,240,255,0.92)');
      g.addColorStop(0.45, 'rgba(138,43,226,0.32)');
      g.addColorStop(1.0, 'rgba(0,0,0,0.0)');
    }

    ctx.fillStyle = g;
    ctx.fillRect(0, 0, size, size);
    const tex = new THREE.CanvasTexture(canvas);
    tex.colorSpace = THREE.SRGBColorSpace;
    return tex;
  }

  function registerLineMaterial(mat) {
    mat.resolution.set(window.innerWidth, window.innerHeight);
    mat.depthWrite = false;
    mat.transparent = true;
    mat.userData.baseOpacity = mat.opacity ?? 1;
    mat.userData.baseLinewidth = mat.linewidth ?? 2.5;
    lineMaterials.push(mat);
    return mat;
  }

  function makeLineMat(color, linewidth = 2.6, opacity = 1.0) {
    return registerLineMaterial(new LineMaterial({
      color,
      linewidth,
      transparent: true,
      opacity,
      worldUnits: false,
      dashed: false,
      alphaToCoverage: true,
      toneMapped: true
    }));
  }

  function createSolidMaterial(colorHex, metalness = 0.8, roughness = 0.25, opacity = 0.34) {
    return new THREE.MeshStandardMaterial({
      color: colorHex,
      metalness,
      roughness,
      transparent: true,
      opacity,
      polygonOffset: true,
      polygonOffsetFactor: 1.5,
      polygonOffsetUnits: 1.5
    });
  }

  function makeNeonMeshMaterial(colorA, colorB) {
    const mat = new THREE.ShaderMaterial({
      uniforms: {
        time: { value: 0 },
        colorA: { value: new THREE.Color(colorA) },
        colorB: { value: new THREE.Color(colorB) }
      },
      vertexShader: `
        varying vec2 vUv;
        varying vec3 vNormal;
        varying vec3 vWorld;

        void main() {
          vUv = uv;
          vec4 world = modelMatrix * vec4(position, 1.0);
          vWorld = world.xyz;
          vNormal = normalize(normalMatrix * normal);
          gl_Position = projectionMatrix * viewMatrix * world;
        }
      `,
      fragmentShader: `
        uniform float time;
        uniform vec3 colorA;
        uniform vec3 colorB;

        varying vec2 vUv;
        varying vec3 vNormal;
        varying vec3 vWorld;

        float hash21(vec2 p) {
          p = fract(p * vec2(123.34, 456.21));
          p += dot(p, p + 45.32);
          return fract(p.x * p.y);
        }

        float noise2D(vec2 p) {
          vec2 i = floor(p);
          vec2 f = fract(p);
          f = f * f * (3.0 - 2.0 * f);
          float a = hash21(i);
          float b = hash21(i + vec2(1.0, 0.0));
          float c = hash21(i + vec2(0.0, 1.0));
          float d = hash21(i + vec2(1.0, 1.0));
          return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
        }

        void main() {
          float n = noise2D(vWorld.xz * 0.12 + time * 0.02);
          float moon = clamp(dot(normalize(vNormal), normalize(vec3(-0.55, 0.75, -0.36))) * 0.5 + 0.5, 0.0, 1.0);

          vec3 base = mix(colorA, colorB, n);
          base *= 0.16 + moon * 0.58;

          vec2 gridUV = fract(vWorld.xz * 0.25);
          float lineW = 0.028;
          float gridX = 1.0 - smoothstep(0.0, lineW, gridUV.x) * smoothstep(1.0, 1.0 - lineW, gridUV.x);
          float gridY = 1.0 - smoothstep(0.0, lineW, gridUV.y) * smoothstep(1.0, 1.0 - lineW, gridUV.y);
          float grid = max(gridX, gridY);
          float distFade = max(0.0, 1.0 - length(vWorld.xz) / 66.0);
          base += vec3(0.02, 0.10, 0.22) * grid * distFade;

          base += vec3(0.01, 0.01, 0.025);
          gl_FragColor = vec4(base, 1.0);
        }
      `
    });

    neonMaterials.push(mat);
    return mat;
  }

  function makeFlameMaterial() {
    const mat = new THREE.ShaderMaterial({
      uniforms: {
        time: { value: 0 },
        power: { value: 1.0 }
      },
      vertexShader: `
        varying vec2 vUv;
        varying vec3 vLocal;

        void main() {
          vUv = uv;
          vLocal = position;
          vec4 mv = modelViewMatrix * vec4(position, 1.0);
          gl_Position = projectionMatrix * mv;
        }
      `,
      fragmentShader: `
        uniform float time;
        uniform float power;

        varying vec2 vUv;
        varying vec3 vLocal;

        float hash(vec2 p) {
          return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453123);
        }

        float noise(vec2 p) {
          vec2 i = floor(p);
          vec2 f = fract(p);
          f = f * f * (3.0 - 2.0 * f);
          float a = hash(i);
          float b = hash(i + vec2(1.0, 0.0));
          float c = hash(i + vec2(0.0, 1.0));
          float d = hash(i + vec2(1.0, 1.0));
          return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
        }

        void main() {
          float tail = 1.0 - vUv.y;
          float core = smoothstep(0.55, 0.0, abs(vUv.x - 0.5));
          float n = noise(vec2(vUv.x * 7.0, vUv.y * 14.0 - time * 8.0));
          float flicker = 0.7 + 0.3 * sin(time * 23.0 + n * 6.0);
          float a = core * smoothstep(1.0, 0.08, vUv.y) * (0.45 + n * 0.85) * flicker * power;

          vec3 hot = vec3(1.0, 0.86, 0.32);
          vec3 orange = vec3(1.0, 0.24, 0.04);
          vec3 magenta = vec3(1.0, 0.03, 0.42);
          vec3 color = mix(hot, orange, smoothstep(0.0, 0.5, vUv.y));
          color = mix(color, magenta, smoothstep(0.42, 1.0, vUv.y));

          gl_FragColor = vec4(color * (1.35 + tail * 0.6), a);
        }
      `,
        transparent: true,
        blending: THREE.AdditiveBlending,
        depthWrite: false,
        side: THREE.DoubleSide
    });

    flameMaterials.push(mat);
    return mat;
  }

  function createSolidWithEdges(geometry, solidMaterial, edgeMaterial) {
    const group = new THREE.Group();

    const mesh = new THREE.Mesh(geometry, solidMaterial);
    group.add(mesh);

    const edges = new THREE.EdgesGeometry(geometry, 15);
    const positions = Array.from(edges.attributes.position.array);
    const g = new LineSegmentsGeometry();
    g.setPositions(positions);
    const lines = new LineSegments2(g, edgeMaterial);
    lines.computeLineDistances();
    group.add(lines);

    return group;
  }

  function edgesToLineSegments(geometry, material, threshold = 10) {
    const edges = new THREE.EdgesGeometry(geometry, threshold);
    const positions = Array.from(edges.attributes.position.array);
    const g = new LineSegmentsGeometry();
    g.setPositions(positions);
    const lines = new LineSegments2(g, material);
    lines.computeLineDistances();
    return lines;
  }

  function pointsToLine2(points, material) {
    const flat = [];
    for (const p of points) flat.push(p.x, p.y, p.z);
    const g = new LineGeometry();
    g.setPositions(flat);
    const line = new Line2(g, material);
    line.computeLineDistances();
    return line;
  }

  function segmentsToLineSegments(segmentsFlatArray, material) {
    const g = new LineSegmentsGeometry();
    g.setPositions(segmentsFlatArray);
    const lines = new LineSegments2(g, material);
    lines.computeLineDistances();
    return lines;
  }

  function buildHologramMaterial(baseColorHex) {
    const mat = new THREE.ShaderMaterial({
      uniforms: {
        time: { value: 0 },
        neonPower: { value: 1.2 },
        baseColor: { value: new THREE.Color(baseColorHex) }
      },
      vertexShader: `
        varying vec2 vUv;
        varying vec3 vViewDir;
        varying vec3 vLocalPos;

        void main() {
          vUv = uv;
          vLocalPos = position;

          vec3 localCam = (inverse(modelMatrix) * vec4(cameraPosition, 1.0)).xyz;
          vViewDir = normalize(position - localCam);

          gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform float time;
        uniform float neonPower;
        uniform vec3 baseColor;
        varying vec2 vUv;
        varying vec3 vViewDir;
        varying vec3 vLocalPos;

        float hash21(vec2 p) {
          return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453123);
        }

        float drawGrid(vec2 uv, float cols, float glowWidth) {
          vec2 g = fract(uv * cols);
          vec2 d = min(g, 1.0 - g);
          float edge = min(d.x, d.y);
          return smoothstep(glowWidth, 0.0, edge);
        }

        void main() {
          vec3 V = normalize(vViewDir);
          vec3 finalCol = vec3(0.0);
          const int LAYERS = 4;

          for (int i = 0; i < LAYERS; i++) {
            float depth = float(i) * 0.15 + 0.05;
            vec2 parallaxOffset = V.xy * (depth / max(abs(V.z), 0.001));
            vec2 layerUv = vUv + parallaxOffset;

            float layerGlow = 0.0;
            vec3 layerColor = baseColor;

            if (i == 0) {
              layerGlow = drawGrid(layerUv, 8.0, 0.012) * 0.35;
              vec2 border = smoothstep(vec2(0.03), vec2(0.0), min(layerUv, 1.0 - layerUv));
              layerGlow += max(border.x, border.y) * 0.8;
              layerColor = mix(baseColor, vec3(1.0, 0.16, 0.55), 0.3);
            } else if (i == 1) {
              vec2 nodeUv = layerUv * 10.0;
              float h = hash21(floor(nodeUv));
              layerGlow = step(0.75, h) * (sin(time * 3.5 + h * 12.0) * 0.5 + 0.5) * 0.8;
              layerGlow += drawGrid(layerUv, 10.0, 0.03) * 0.25;
              layerColor = vec3(0.0, 0.94, 1.0);
            } else if (i == 2) {
              float flow = sin(layerUv.y * 24.0 - time * 5.0) * 0.5 + 0.5;
              float blocks = step(0.88, hash21(floor(layerUv * vec2(12.0, 6.0)) + vec2(0.0, floor(time * 3.0))));
              layerGlow = blocks * flow * 0.95;
              layerColor = vec3(1.0, 0.72, 0.1);
            } else {
              float dist = length(layerUv - vec2(0.5));
              float ring = smoothstep(0.035, 0.0, abs(dist - 0.28 + sin(time) * 0.04));
              layerGlow = ring * 1.6;
              layerColor = mix(vec3(0.66, 0.0, 1.0), baseColor, 0.5);
            }

            float fade = 1.0 - (float(i) / float(LAYERS));
            finalCol += layerColor * layerGlow * fade * (0.8 + 0.35 * sin(time * 2.0 + float(i)));
          }

          finalCol *= (0.6 + neonPower * 0.5);
          finalCol = finalCol / (finalCol + vec3(0.18)); 

          gl_FragColor = vec4(finalCol, max(finalCol.r, max(finalCol.g, finalCol.b)) * 0.9 + 0.1);
        }
      `,
      transparent: true,
      side: THREE.DoubleSide
    });

    neonMaterials.push(mat);
    return mat;
  }

  function buildInstancedFoliageMaterial() {
    return new THREE.ShaderMaterial({
      uniforms: {
        time: { value: 0 },
        rate: { value: 1.0 },
        neonPower: { value: 1.2 },
        baseColor: { value: new THREE.Color('#021008') },
        neonLeaves: { value: new THREE.Color('#7cff6b') }
      },
      vertexShader: `
        attribute vec2 aFlickerParams;
        attribute vec2 aWindParams;

        uniform float time;
        uniform float rate;

        varying vec3 vNormal;
        varying vec2 vUv;
        varying vec3 vWorldPos;
        varying float vFlicker;

        void main() {
          vUv = uv;
          vNormal = normalize(normalMatrix * normal);

          vec4 localPosition = instanceMatrix * vec4(position, 1.0);

          float heightFactor = max(0.0, position.y);
          float sway = sin(time * rate * 2.2 + aWindParams.x) * aWindParams.y * 0.18 * heightFactor;
          localPosition.x += sway;
          localPosition.z += sway * 0.4;

          vec4 worldPos = modelMatrix * localPosition;
          vWorldPos = worldPos.xyz;

          vFlicker = 0.82 + 0.18 * sin(time * rate * aFlickerParams.y + aFlickerParams.x);

          gl_Position = projectionMatrix * viewMatrix * worldPos;
        }
      `,
      fragmentShader: `
        uniform float neonPower;
        uniform vec3 baseColor;
        uniform vec3 neonLeaves;

        varying vec3 vNormal;
        varying vec2 vUv;
        varying vec3 vWorldPos;
        varying float vFlicker;

        void main() {
          float diffuse = clamp(dot(normalize(vNormal), normalize(vec3(-0.55, 0.75, -0.36))) * 0.5 + 0.5, 0.0, 1.0);
          
          float pattern = smoothstep(0.4, 0.45, sin(vUv.y * 12.0) * cos(vUv.x * 8.0));
          vec3 col = mix(baseColor, neonLeaves * vFlicker * neonPower, pattern * 0.8);
          col *= (0.2 + diffuse * 0.8);

          gl_FragColor = vec4(col, 0.88);
        }
      `,
      transparent: true
    });
  }

  function buildInstancedHutMaterial() {
    return new THREE.ShaderMaterial({
      uniforms: {
        time: { value: 0 },
        rate: { value: 1.0 },
        neonPower: { value: 1.2 },
        baseColor: { value: new THREE.Color('#050711') },
        neonA: { value: new THREE.Color('#00f0ff') },
        neonB: { value: new THREE.Color('#a855f7') }
      },
      vertexShader: `
        attribute vec2 aFlickerParams;
        
        uniform float time;
        uniform float rate;

        varying vec3 vNormal;
        varying vec2 vUv;
        varying vec3 vWorldPos;
        varying float vFlicker;

        void main() {
          vUv = uv;
          vNormal = normalize(normalMatrix * normal);

          vec4 localPosition = instanceMatrix * vec4(position, 1.0);
          vec4 worldPos = modelMatrix * localPosition;
          vWorldPos = worldPos.xyz;

          vFlicker = 0.8 + 0.2 * sin(time * rate * aFlickerParams.y + aFlickerParams.x);
          gl_Position = projectionMatrix * viewMatrix * worldPos;
        }
      `,
      fragmentShader: `
        uniform float neonPower;
        uniform vec3 baseColor;
        uniform vec3 neonA;
        uniform vec3 neonB;

        varying vec3 vNormal;
        varying vec2 vUv;
        varying vec3 vWorldPos;
        varying float vFlicker;

        void main() {
          float diff = clamp(dot(normalize(vNormal), normalize(vec3(-0.55, 0.75, -0.36))) * 0.5 + 0.5, 0.0, 1.0);

          float grid = step(0.94, fract(vUv.x * 4.0)) + step(0.94, fract(vUv.y * 4.0));
          vec3 neonColor = mix(neonA, neonB, sin(vWorldPos.y * 0.5) * 0.5 + 0.5);

          vec3 col = mix(baseColor, neonColor * vFlicker * neonPower, grid * 0.75);
          col *= (0.15 + diff * 0.85);

          gl_FragColor = vec4(col, 0.9);
        }
      `,
      transparent: true
    });
  }

  function buildBitStreamRoadMaterial() {
    return new THREE.ShaderMaterial({
      uniforms: {
        time: { value: 0 },
        neonPower: { value: 1.2 },
        colorA: { value: new THREE.Color('#00f0ff') },
        colorB: { value: new THREE.Color('#ff2a85') }
      },
      vertexShader: `
        varying vec2 vUv;
        varying vec3 vWorld;

        void main() {
          vUv = uv;
          vec4 world = modelMatrix * vec4(position, 1.0);
          vWorld = world.xyz;
          gl_Position = projectionMatrix * viewMatrix * world;
        }
      `,
      fragmentShader: `
        uniform float time;
        uniform float neonPower;
        uniform vec3 colorA;
        uniform vec3 colorB;

        varying vec2 vUv;
        varying vec3 vWorld;

        float hash21(vec2 p) {
          return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453123);
        }

        void main() {
          float lanes = 6.0;
          float laneId = floor(vUv.x * lanes);
          float localLaneX = fract(vUv.x * lanes);

          float speed = (sin(laneId * 23.45) * 0.4 + 1.2) * 2.3;
          float direction = (hash21(vec2(laneId, 12.34)) > 0.5) ? 1.0 : -1.0;

          float streamUvY = vUv.y * 14.0 - time * speed * direction;
          float segmentId = floor(streamUvY);
          float segmentFrac = fract(streamUvY);

          float packetHash = hash21(vec2(laneId, segmentId));
          float isPacket = step(0.68, packetHash); 

          float packetLen = hash21(vec2(laneId + 1.15, segmentId)) * 0.5 + 0.18;
          float activePackets = step(1.0 - packetLen, segmentFrac);

          vec3 packetColor = mix(colorA, colorB, sin(laneId + time * 0.6) * 0.5 + 0.5);
          vec3 finalRoad = vec3(0.015, 0.018, 0.03) * (1.0 - activePackets);

          if (isPacket > 0.5 && activePackets > 0.5) {
            finalRoad += packetColor * 2.8 * neonPower;
          }

          float edgeMarker = step(0.95, localLaneX) + step(localLaneX, 0.05);
          float dividerLine = step(0.72, fract(vUv.y * 22.0));
          finalRoad += vec3(0.0, 0.85, 1.0) * edgeMarker * dividerLine * 0.35 * neonPower;

          finalRoad = finalRoad / (finalRoad + vec3(0.12));

          gl_FragColor = vec4(finalRoad, 1.0);
        }
      `
    });
  }

  function buildCurlNoiseSpecksMaterial() {
    const mat = new THREE.ShaderMaterial({
      uniforms: {
        time: { value: 0 },
        rate: { value: 1.0 },
        atmosphereIntensity: { value: 1.0 }, 
        colorA: { value: new THREE.Color('#00f0ff') },
        colorB: { value: new THREE.Color('#ff2a85') }
      },
      vertexShader: `
        uniform float time;
        uniform float rate;
        uniform float atmosphereIntensity;

        attribute float phase;
        varying float vAlpha;
        varying float vMix;

        vec3 mod289(vec3 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
        vec4 mod289(vec4 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
        vec4 permute(vec4 x) { return mod289(((x*34.0)+1.0)*x); }
        vec4 taylorInvSqrt(vec4 r) { return 1.79284291400159 - 0.85373472095314 * r; }

        float snoise(vec3 v){
          const vec2 C = vec2(1.0/6.0, 1.0/3.0);
          const vec4 D = vec4(0.0, 0.5, 1.0, 2.0);
          
          vec3 i  = floor(v + dot(v, C.yyy) );
          vec3 x0 = v - i + dot(i, C.xxx) ;
          
          vec3 g = step(x0.yzx, x0.xyz);
          vec3 l = 1.0 - g;
          vec3 i1 = min( g.xyz, l.zxy );
          vec3 i2 = max( g.xyz, l.zxy );
          
          vec3 x1 = x0 - i1 + C.xxx;
          vec3 x2 = x0 - i2 + C.yyy;
          vec3 x3 = x0 - D.yyy;
          
          i = mod289(i); 
          vec4 p = permute( permute( permute(
                             i.z + vec4(0.0, i1.z, i2.z, 1.0) )
                           + i.y + vec4(0.0, i1.y, i2.y, 1.0) )
                           + i.x + vec4(0.0, i1.x, i2.x, 1.0) );
                           
          float n_ = 0.142857142857; 
          vec3  ns = n_ * D.wyz - D.xzx;
          vec4 j = p - 49.0 * floor(p * ns.z);
          
          vec4 x_ = floor(j * ns.z);
          vec4 y_ = floor(j - 7.0 * x_ );
          
          vec4 x = x_ *ns.x + ns.yyyy;
          vec4 y = y_ *ns.x + ns.yyyy;
          vec4 h = 1.0 - abs(x) - abs(y);
          
          vec4 b0 = vec4( x.xy, y.xy );
          vec4 b1 = vec4( x.zw, y.zw );
          
          vec4 s0 = floor(b0)*2.0 + 1.0;
          vec4 s1 = floor(b1)*2.0 + 1.0;
          vec4 sh = -step(h, vec4(0.0));
          
          vec4 a0 = b0.xzyw + s0.xzyw*sh.xxyy ;
          vec4 a1 = b1.xzyw + s1.zzww*sh.zzww ; 
          
          vec3 p0 = vec3(a0.xy,h.x);
          vec3 p1 = vec3(a0.zw,h.y);
          vec3 p2 = vec3(a1.xy,h.z);
          vec3 p3 = vec3(a1.zw,h.w);
          
          vec4 r_norm = taylorInvSqrt(vec4(dot(p0,p0), dot(p1,p1), dot(p2, p2), dot(p3,p3)));
          p0 *= r_norm.x;
          p1 *= r_norm.y;
          p2 *= r_norm.z;
          p3 *= r_norm.w;
          
          vec4 m = max(0.6 - vec4(dot(x0,x0), dot(x1,x1), dot(x2,x2), dot(x3,x3)), 0.0);
          m = m * m;
          return 42.0 * dot( m*m, vec4( dot(p0,x0), dot(p1,x1),
                                        dot(p2,x2), dot(p3,x3) ) );
        }

        vec3 curlNoise(vec3 p) {
          float e = 0.08;
          vec3 p_x = p + vec3(e, 0.0, 0.0);
          vec3 p_y = p + vec3(0.0, e, 0.0);
          vec3 p_z = p + vec3(0.0, 0.0, e);

          float val_x = snoise(p_y) - snoise(p_z);
          float val_y = snoise(p_z) - snoise(p_x);
          float val_z = snoise(p_x) - snoise(p_y);

          return normalize(vec3(val_x, val_y, val_z));
        }

        void main() {
          vec3 pos = position;

          vec3 flow = curlNoise(pos * 0.038 + vec3(0.0, time * rate * 0.12, 0.0));
          pos += flow * (4.5 * atmosphereIntensity);

          vec4 mvPosition = modelViewMatrix * vec4(pos, 1.0);
          gl_PointSize = 22.0 / -mvPosition.z;
          gl_Position = projectionMatrix * mvPosition;

          vAlpha = 0.22 + 0.48 * sin(time * 1.5 + phase) * 0.5 + 0.35;
          vMix = sin(phase) * 0.5 + 0.5;
        }
      `,
      fragmentShader: `
        uniform vec3 colorA;
        uniform vec3 colorB;
        varying float vAlpha;
        varying float vMix;

        void main() {
          vec2 coord = gl_PointCoord - vec2(0.5);
          float d = length(coord);
          if (d > 0.5) discard;
          float glow = 1.0 - d * 2.0;
          vec3 color = mix(colorA, colorB, vMix);
          gl_FragColor = vec4(color * glow, vAlpha * glow * 0.65);
        }
      `,
      transparent: true,
      blending: THREE.AdditiveBlending,
      depthWrite: false
    });

    return mat;
  }

  const ChromaticInterferenceShader = {
    uniforms: {
      tDiffuse: { value: null },
      time: { value: 0 },
      drift: { value: 0.25 },
      neonPower: { value: 1.2 }
    },
    vertexShader: `
      varying vec2 vUv;
      void main() {
        vUv = uv;
        gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      }
    `,
    fragmentShader: `
      uniform sampler2D tDiffuse;
      uniform float time;
      uniform float drift;
      uniform float neonPower;
      varying vec2 vUv;

      void main() {
        vec2 uv = vUv;
        vec2 dir = uv - vec2(0.5);

        vec2 offset = dir * (0.015 * drift);

        vec4 cr = texture2D(tDiffuse, uv - offset);
        vec4 cg = texture2D(tDiffuse, uv);
        vec4 cb = texture2D(tDiffuse, uv + offset);

        vec3 finalColor = vec3(cr.r, cg.g, cb.b);

        finalColor *= (1.0 + neonPower * 0.12);
        finalColor = finalColor / (finalColor + vec3(0.14));

        gl_FragColor = vec4(finalColor, 1.0);
      }
    `
  };

  function init() {
    scene = new THREE.Scene();
    scene.background = new THREE.Color('#030108');

    camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.1, 300);
    camera.position.set(28, 17, 42);

    renderer = new THREE.WebGLRenderer({
      antialias: false,
      powerPreference: 'high-performance'
    });
    renderer.setSize(window.innerWidth, window.innerHeight);
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.outputColorSpace = THREE.SRGBColorSpace;
    renderer.toneMapping = THREE.ACESFilmicToneMapping;
    renderer.toneMappingExposure = 1.12;
    document.getElementById('canvas-container').appendChild(renderer.domElement);

    composer = new EffectComposer(renderer);
    composer.addPass(new RenderPass(scene, camera));

    bloomPass = new UnrealBloomPass(
      new THREE.Vector2(window.innerWidth, window.innerHeight),
      state.bloom, 
      0.58,
      0.18
    );
    bloomPass.threshold = 0.16;
    bloomPass.radius = 0.62;
    composer.addPass(bloomPass);

    screenPass = new ShaderPass(ChromaticInterferenceShader);
    composer.addPass(screenPass);
    composer.addPass(new OutputPass());

    controls = new OrbitControls(camera, renderer.domElement);
    controls.enableDamping = true;
    controls.dampingFactor = 0.05;
    controls.target.set(0, 3.2, 0);
    controls.minDistance = 10;
    controls.maxDistance = 100;
    controls.maxPolarAngle = Math.PI * 0.49;

    clock = new THREE.Clock();
    scene.add(villageGroup);

    landmarks.church.x = roadCurveX(landmarks.church.z) + 18.0;
    landmarks.clockTower.x = roadCurveX(landmarks.clockTower.z) - 16.0;
    landmarks.billboard.x = roadCurveX(landmarks.billboard.z) - 18.5;

    setupUI();
    buildMaterials();
    buildLighting();
    buildTerrain();
    buildRoad();
    buildRoadDetails();
    buildMoon();
    buildBackgroundRidges();
    buildLandmarks();
    buildInstancedStructures();
    buildNeonBillboard();
    buildAtmosphereSpecks();
    buildDrones();
    buildDragons(); 

    window.addEventListener('resize', onResize);
    document.getElementById('loader').style.opacity = '0';
    animate();
  }

  function setupUI() {
    const panel = document.getElementById('micro-ui');
    const toggle = document.getElementById('ui-toggle');

    toggle.addEventListener('click', () => {
      panel.classList.toggle('minimized');
      toggle.innerText = panel.classList.contains('minimized') ? '+' : '−';
    });

    if (window.innerWidth <= 768) {
      panel.classList.add('minimized');
      toggle.innerText = '+';
    }

    bindSlider('rate', 'rate');
    bindSlider('neon', 'neon');
    bindSlider('fog', 'fog');
    bindSlider('bloom', 'bloom', (val) => {
      if (bloomPass) bloomPass.strength = val;
    });
    bindSlider('drift', 'drift');
  }

  function setRangeProgress(el) {
    const min = parseFloat(el.min || '0');
    const max = parseFloat(el.max || '100');
    const value = parseFloat(el.value || '0');
    const pct = ((value - min) / (max - min)) * 100;
    el.style.setProperty('--fill', `${Math.max(0, Math.min(100, pct))}%`);
  }

  function bindSlider(id, key, callback) {
    const el = document.getElementById(id);
    const valueEl = document.getElementById(`val-${id}`);

    const sync = () => {
      const val = parseFloat(el.value);
      state[key] = val;
      valueEl.textContent = val.toFixed(2);
      setRangeProgress(el);
      if (callback) callback(val);
    };

    el.addEventListener('input', sync);
    sync();
  }

  function buildMaterials() {
    terrainMaterial = makeNeonMeshMaterial('#020713', '#070b20');
    roadMaterial = buildBitStreamRoadMaterial();

    solidBuildingMaterial = createSolidMaterial(0x050711, 0.72, 0.28, 0.38);
    solidFoliageMaterial = createSolidMaterial(0x021008, 0.42, 0.74, 0.28);
    solidRockMaterial = createSolidMaterial(0x140702, 0.6, 0.5, 0.42);

    instancedHutMaterial = buildInstancedHutMaterial();
    instancedFoliageMaterial = buildInstancedFoliageMaterial();
    hologramMaterial = buildHologramMaterial('#00f0ff');

    moonMaterial = new THREE.ShaderMaterial({
      uniforms: { time: { value: 0 } },
      vertexShader: `
        varying vec2 vUv;
        varying vec3 vNormal;
        varying vec3 vView;

        void main() {
          vUv = uv;
          vec4 vPos = modelViewMatrix * vec4(position, 1.0);
          vView = -vPos.xyz;
          vNormal = normalize(normalMatrix * normal);
          gl_Position = projectionMatrix * vPos;
        }
      `,
      fragmentShader: `
        uniform float time;
        varying vec2 vUv;
        varying vec3 vNormal;
        varying vec3 vView;

        float hash(vec2 p) {
          return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453);
        }

        float noise(vec2 p) {
          vec2 i = floor(p);
          vec2 f = fract(p);
          f = f * f * (3.0 - 2.0 * f);
          return mix(mix(hash(i), hash(i + vec2(1.0, 0.0)), f.x),
                     mix(hash(i + vec2(0.0, 1.0)), hash(i + vec2(1.0, 1.0)), f.x), f.y);
        }

        void main() {
          float n1 = noise(vUv * 20.0);
          float n2 = noise(vUv * 55.0 + vec2(time * 0.01));
          float craters = smoothstep(0.38, 0.62, n1) * smoothstep(0.72, 0.28, n2);
          float fresnel = pow(1.0 - max(dot(normalize(vNormal), normalize(vView)), 0.0), 3.0);

          vec3 c1 = vec3(0.62, 0.16, 0.95);
          vec3 c2 = vec3(0.0, 0.88, 1.0);
          vec3 c3 = vec3(1.0, 0.12, 0.52);

          vec3 color = mix(c2, c1, craters * 0.85);
          color = mix(color, c3, fresnel * 0.35);
          color += vec3(1.0) * fresnel * 0.7;

          gl_FragColor = vec4(color, 1.0);
        }
      `
    });

    neonMaterials.push(moonMaterial);

    lanternMaterial = new THREE.ShaderMaterial({
      uniforms: { time: { value: 0 } },
      vertexShader: `
        varying vec3 vNormal;
        varying vec3 vWorld;

        void main() {
          vec4 world = modelMatrix * vec4(position, 1.0);
          vWorld = world.xyz;
          vNormal = normalize(normalMatrix * normal);
          gl_Position = projectionMatrix * viewMatrix * world;
        }
      `,
      fragmentShader: `
        uniform float time;
        varying vec3 vNormal;
        varying vec3 vWorld;

        void main() {
          float pulse = 0.82 + sin(time * 6.0 + vWorld.x + vWorld.z) * 0.18;
          vec3 color = mix(vec3(0.0, 0.9, 1.0), vec3(1.0, 0.05, 0.45), 0.18) * pulse;
          gl_FragColor = vec4(color, 0.92);
        }
      `,
      transparent: true,
      blending: THREE.AdditiveBlending,
      depthWrite: false
    });

    neonMaterials.push(lanternMaterial);
    flameMaterial = makeFlameMaterial();

    churchGlassMaterial = new THREE.ShaderMaterial({
      uniforms: { time: { value: 0 } },
      vertexShader: `
        varying vec2 vUv;
        void main() {
          vUv = uv;
          gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform float time;
        varying vec2 vUv;

        void main() {
          vec2 uv = vUv - vec2(0.5);
          float r = length(uv);
          float theta = atan(uv.y, uv.x);

          float p1 = sin(r * 28.0 - time * 1.8) * sin(theta * 10.0);
          float p2 = cos(r * 48.0 + time * 1.2) * cos(theta * 8.0 - time * 0.4);
          float ring = smoothstep(0.48, 0.45, r) * smoothstep(0.01, 0.05, r);

          float finalPat = (p1 * 0.5 + p2 * 0.5) * ring;

          vec3 violet = vec3(0.35, 0.02, 0.82);
          vec3 magenta = vec3(1.0, 0.0, 0.58);
          vec3 cyan = vec3(0.0, 0.92, 1.0);

          vec3 color = mix(violet, magenta, sin(time * 0.6 + r * 5.5) * 0.5 + 0.5);
          color = mix(color, cyan, finalPat * 0.65);
          color += vec3(0.18, 0.0, 0.28) * (1.0 - r * 2.0);

          float lead = smoothstep(0.03, 0.0, abs(sin(r * 42.0)) * 0.1);
          lead += smoothstep(0.03, 0.0, abs(sin(theta * 10.0)) * 0.06);
          color *= mix(1.0, 0.12, lead * ring);

          float edge = smoothstep(0.44, 0.48, r);
          color = mix(color, magenta * 1.6, edge);

          gl_FragColor = vec4(color * (1.3 + 0.22 * sin(time * 3.4)), ring * 0.95 + edge * 0.5);
        }
      `,
      transparent: true,
      side: THREE.DoubleSide,
      depthWrite: false,
      blending: THREE.AdditiveBlending
    });

    neonMaterials.push(churchGlassMaterial);
  }

  function buildLighting() {
    const hemi = new THREE.HemisphereLight(0x3a0088, 0x050114, 0.72);
    scene.add(hemi);

    const moonLight = new THREE.DirectionalLight(0x00d4ff, 2.55);
    moonLight.position.copy(moonDirection).multiplyScalar(60);
    scene.add(moonLight);

    const underLight = new THREE.PointLight(0xa855f7, 1.15, 75, 2.0);
    underLight.position.set(0, 8, 0);
    scene.add(underLight);

    const warmCityLight = new THREE.PointLight(0xff2a85, 1.05, 52, 2.0);
    warmCityLight.position.set(12, 7, 8);
    scene.add(warmCityLight);
  }

  function buildTerrain() {
    const geo = new THREE.PlaneGeometry(120, 120, 64, 64);
    geo.rotateX(-Math.PI / 2);

    const pos = geo.attributes.position;
    for (let i = 0; i < pos.count; i++) {
      const x = pos.getX(i);
      const z = pos.getZ(i);
      pos.setY(i, terrainHeight(x, z));
    }
    geo.computeVertexNormals();

    const mesh = new THREE.Mesh(geo, terrainMaterial);
    villageGroup.add(mesh);
  }

  function buildRoad() {
    const width = 6.0;
    const length = 100;
    const segments = 120;

    const positions = [];
    const uvs = [];
    const indices = [];
    const leftPts = [];
    const rightPts = [];
    const outerLeftPts = [];
    const outerRightPts = [];

    for (let i = 0; i <= segments; i++) {
      const t = i / segments;
      const z = -length * 0.5 + t * length;
      const cx = roadCurveX(z);
      const dx = roadDerivative(z);

      const nx = 1.0;
      const nz = -dx;
      const inv = 1.0 / Math.sqrt(nx * nx + nz * nz);
      const ox = nx * inv * width * 0.5;
      const oz = nz * inv * width * 0.5;

      const leftX = cx - ox;
      const leftZ = z - oz;
      const rightX = cx + ox;
      const rightZ = z + oz;

      const outerOffset = 0.7;
      const oox = nx * inv * (width * 0.5 + outerOffset);
      const ooz = nz * inv * (width * 0.5 + outerOffset);

      const yL = terrainHeight(leftX, leftZ) + 0.05;
      const yR = terrainHeight(rightX, rightZ) + 0.05;
      const yOL = terrainHeight(cx - oox, z - ooz) + 0.12;
      const yOR = terrainHeight(cx + oox, z + ooz) + 0.12;

      positions.push(leftX, yL, leftZ, rightX, yR, rightZ);
      uvs.push(0, t, 1, t);

      leftPts.push(new THREE.Vector3(leftX, yL + 0.025, leftZ));
      rightPts.push(new THREE.Vector3(rightX, yR + 0.025, rightZ));
      outerLeftPts.push(new THREE.Vector3(cx - oox, yOL, z - ooz));
      outerRightPts.push(new THREE.Vector3(cx + oox, yOR, z + ooz));
    }

    for (let i = 0; i < segments; i++) {
      const a = i * 2;
      indices.push(a, a + 1, a + 2, a + 1, a + 3, a + 2);
    }

    const roadGeo = new THREE.BufferGeometry();
    roadGeo.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
    roadGeo.setAttribute('uv', new THREE.Float32BufferAttribute(uvs, 2));
    roadGeo.setIndex(indices);
    roadGeo.computeVertexNormals();

    const roadMesh = new THREE.Mesh(roadGeo, roadMaterial);
    villageGroup.add(roadMesh);

    const edgeMat = makeLineMat('#00f0ff', 3.6, 1.0);
    const outerEdgeMat = makeLineMat('#ff2a85', 2.1, 0.72);

    villageGroup.add(
      pointsToLine2(leftPts, edgeMat),
      pointsToLine2(rightPts, edgeMat),
      pointsToLine2(outerLeftPts, outerEdgeMat),
      pointsToLine2(outerRightPts, outerEdgeMat)
    );
  }

  function buildRoadDetails() {
    const dashMat = makeLineMat('#ffe56b', 2.2, 0.72);
    const railMat = makeLineMat('#00f0ff', 1.4, 0.35);

    for (let z = -43; z <= 43; z += 7) {
      const cx = roadCurveX(z);
      const dx = roadDerivative(z);
      const angle = Math.atan2(dx, 1.0);

      const y = terrainHeight(cx, z) + 0.16;
      const dash = new THREE.Group();

      const pts = [
        new THREE.Vector3(0, 0, -1.4),
        new THREE.Vector3(0, 0, 1.4)
      ];

      const line = pointsToLine2(pts, dashMat);
      dash.add(line);

      dash.position.set(cx, y, z);
      dash.rotation.y = angle;
      villageGroup.add(dash);
      dynamicObjects.roadDashes.push({ mesh: dash, phase: z * 0.13 });
    }

    for (let side = -1; side <= 1; side += 2) {
      const segments = [];
      for (let z = -44; z < 44; z += 8) {
        const cx1 = roadCurveX(z);
        const cx2 = roadCurveX(z + 4);
        const dx1 = roadDerivative(z);
        const dx2 = roadDerivative(z + 4);

        const inv1 = 1 / Math.sqrt(1 + dx1 * dx1);
        const inv2 = 1 / Math.sqrt(1 + dx2 * dx2);

        const x1 = cx1 + side * 4.8 * inv1;
        const z1 = z - side * dx1 * 4.8 * inv1;
        const x2 = cx2 + side * 4.8 * inv2;
        const z2 = z + 4 - side * dx2 * 4.8 * inv2;

        const y1 = terrainHeight(x1, z1) + 0.65;
        const y2 = terrainHeight(x2, z2) + 0.65;

        segments.push(x1, y1, z1, x2, y2, z2);
      }

      villageGroup.add(segmentsToLineSegments(segments, railMat));
    }
  }

  function buildMoon() {
    const moon = new THREE.Mesh(new THREE.SphereGeometry(6.0, 64, 64), moonMaterial);
    moon.position.set(-35, 38, -50);
    scene.add(moon);

    const glowTexture = createGlowTexture();
    const glowMat = new THREE.SpriteMaterial({
      map: glowTexture,
      color: 0x9922ff,
      transparent: true,
      opacity: 0.58,
      blending: THREE.AdditiveBlending,
      depthWrite: false
    });

    const glow = new THREE.Sprite(glowMat);
    glow.position.copy(moon.position);
    glow.scale.set(35, 35, 1);
    scene.add(glow);
  }

  function buildBackgroundRidges() {
    const ridgeMatA = makeLineMat('#00f0ff', 2.0, 0.38);
    const ridgeMatB = makeLineMat('#a855f7', 1.5, 0.26);
    const ridgeMatC = makeLineMat('#ff2a85', 1.2, 0.22);

    function makeRidge(zOffset, amplitude, heightBase, count, material) {
      const pts = [];
      for (let i = 0; i < count; i++) {
        const t = i / (count - 1);
        const x = -65 + t * 130;
        const y = heightBase +
          Math.sin(t * Math.PI * 6.0 + zOffset) * amplitude +
          Math.cos(t * Math.PI * 9.0) * (amplitude * 0.4);
        pts.push(new THREE.Vector3(x, y, zOffset));
      }
      return pointsToLine2(pts, material);
    }

    villageGroup.add(
      makeRidge(-55, 6.0, 10.0, 60, ridgeMatA),
      makeRidge(-60, 5.0, 14.0, 50, ridgeMatB),
      makeRidge(55, 4.0, 8.0, 40, ridgeMatB),
      makeRidge(62, 5.8, 12.0, 48, ridgeMatC)
    );
  }

  function createChurchTemplate() {
    const church = new THREE.Group();

    const neonPurple = makeLineMat('#a855f7', 3.0, 0.95);
    const neonPink = makeLineMat('#ff2a85', 2.8, 1.0);
    const neonCyan = makeLineMat('#00f0ff', 2.6, 1.0);
    const neonAmber = makeLineMat('#ffb84a', 2.0, 0.86);

    const f1 = createSolidWithEdges(new THREE.BoxGeometry(8.0, 1.2, 14.0), solidBuildingMaterial, neonPurple);
    f1.position.y = 0.6;
    church.add(f1);

    const f2 = createSolidWithEdges(new THREE.BoxGeometry(7.0, 0.8, 13.0), solidBuildingMaterial, neonPink);
    f2.position.y = 1.6;
    church.add(f2);

    const hallGeo = new THREE.BoxGeometry(5.2, 6.0, 10.0);
    const hall = createSolidWithEdges(hallGeo, solidBuildingMaterial, neonCyan);
    hall.position.set(0, 5.0, -1.0);
    church.add(hall);

    const apseGeo = new THREE.CylinderGeometry(2.6, 2.6, 6.0, 8, 1, false, 0, Math.PI);
    apseGeo.rotateY(Math.PI / 2);
    const apse = createSolidWithEdges(apseGeo, solidBuildingMaterial, neonPurple);
    apse.position.set(0, 5.0, -6.0);
    church.add(apse);

    for (let side = -1; side <= 1; side += 2) {
      const zs = [-4.0, -1.0, 2.0];
      for (const bz of zs) {
        const pier = createSolidWithEdges(new THREE.BoxGeometry(0.6, 5.0, 0.6), solidBuildingMaterial, neonPink);
        pier.position.set(side * 4.0, 2.5, bz);
        church.add(pier);

        const flyerGeo = new THREE.BoxGeometry(1.8, 0.25, 0.25);
        const flyer = createSolidWithEdges(flyerGeo, solidBuildingMaterial, neonCyan);
        flyer.position.set(side * 2.9, 4.6, bz);
        flyer.rotation.z = side * -0.42;
        church.add(flyer);

        const pSpireGeo = new THREE.ConeGeometry(0.3, 1.2, 4);
        const pSpire = createSolidWithEdges(pSpireGeo, solidBuildingMaterial, neonAmber);
        pSpire.position.set(side * 4.0, 5.6, bz);
        church.add(pSpire);
      }
    }

    const tower = createSolidWithEdges(new THREE.BoxGeometry(2.6, 12.0, 2.6), solidBuildingMaterial, neonCyan);
    tower.position.set(0, 8.0, 5.3);
    church.add(tower);

    const spireGeo = new THREE.ConeGeometry(1.5, 8.0, 8);
    const spire = createSolidWithEdges(spireGeo, solidBuildingMaterial, neonPink);
    spire.position.set(0, 18.0, 5.3);
    church.add(spire);

    const crossGroup = new THREE.Group();
    const vertCross = createSolidWithEdges(new THREE.BoxGeometry(0.15, 1.8, 0.15), solidBuildingMaterial, neonAmber);
    const horizCross = createSolidWithEdges(new THREE.BoxGeometry(1.1, 0.15, 0.15), solidBuildingMaterial, neonAmber);
    horizCross.position.y = 0.45;
    crossGroup.add(vertCross, horizCross);
    crossGroup.position.set(0, 22.8, 5.3);
    church.add(crossGroup);

    const roseGeo = new THREE.CircleGeometry(1.2, 32);
    const roseMesh = new THREE.Mesh(roseGeo, churchGlassMaterial);
    roseMesh.position.set(0, 9.5, 6.62);
    church.add(roseMesh);

    const roseFrame = edgesToLineSegments(new THREE.RingGeometry(1.2, 1.3, 32), neonPink);
    roseFrame.position.set(0, 9.5, 6.64);
    church.add(roseFrame);

    const portal = createSolidWithEdges(new THREE.BoxGeometry(1.5, 2.6, 0.4), solidBuildingMaterial, neonAmber);
    portal.position.set(0, 3.3, 6.5);
    church.add(portal);

    const portalGlow = new THREE.Mesh(new THREE.PlaneGeometry(1.0, 2.2), new THREE.MeshBasicMaterial({
      color: 0xffa500,
      transparent: true,
      opacity: 0.65,
      side: THREE.DoubleSide
    }));
    portalGlow.position.set(0, 3.1, 6.72);
    church.add(portalGlow);

    return church;
  }

  function createClockTowerTemplate() {
    const clockTower = new THREE.Group();

    const ctEdgeCyan = makeLineMat('#00f0ff', 2.8, 1.0);
    const ctEdgePink = makeLineMat('#ff2a85', 2.8, 1.0);
    const ctEdgePurple = makeLineMat('#a855f7', 2.6, 0.95);
    const ctEdgeAmber = makeLineMat('#ffb84a', 2.0, 0.85);

    const f1 = createSolidWithEdges(new THREE.BoxGeometry(5.2, 1.5, 5.2), solidBuildingMaterial, ctEdgePurple);
    f1.position.y = 0.75;
    clockTower.add(f1);

    const f2 = createSolidWithEdges(new THREE.BoxGeometry(4.2, 1.5, 4.2), solidBuildingMaterial, ctEdgeCyan);
    f2.position.y = 2.25;
    clockTower.add(f2);

    const core = createSolidWithEdges(new THREE.BoxGeometry(1.8, 12.0, 1.8), solidBuildingMaterial, ctEdgePurple);
    core.position.y = 9.0;
    clockTower.add(core);

    const colPos = [-1.6, 1.6];
    for (const cx of colPos) {
      for (const cz of colPos) {
        const col = createSolidWithEdges(new THREE.BoxGeometry(0.35, 12.0, 0.35), solidBuildingMaterial, ctEdgeCyan);
        col.position.set(cx, 9.0, cz);
        clockTower.add(col);
      }
    }

    const braceSegments = [];
    for (let yLevel = 3.0; yLevel < 14.0; yLevel += 3.0) {
      braceSegments.push(
        -1.6, yLevel, -1.6,  -1.6, yLevel + 3.0, 1.6,
        -1.6, yLevel, 1.6,   -1.6, yLevel + 3.0, -1.6,
        1.6, yLevel, -1.6,   1.6, yLevel + 3.0, 1.6,
        1.6, yLevel, 1.6,    1.6, yLevel + 3.0, -1.6,
        -1.6, yLevel, -1.6,  1.6, yLevel + 3.0, -1.6,
        1.6, yLevel, -1.6,   -1.6, yLevel + 3.0, -1.6,
        -1.6, yLevel, 1.6,   1.6, yLevel + 3.0, 1.6,
        1.6, yLevel, 1.6,    -1.6, yLevel + 3.0, 1.6
      );
    }
    const braces = segmentsToLineSegments(braceSegments, ctEdgePink);
    clockTower.add(braces);

    const deck = createSolidWithEdges(new THREE.BoxGeometry(3.8, 0.4, 3.8), solidBuildingMaterial, ctEdgePink);
    deck.position.y = 15.2;
    clockTower.add(deck);

    const railingGeo = new THREE.BoxGeometry(3.6, 0.6, 3.6);
    const railing = edgesToLineSegments(railingGeo, ctEdgeCyan);
    railing.position.y = 15.7;
    clockTower.add(railing);

    const beaconLight = new THREE.PointLight(0x00f0ff, 2.5, 18.0, 2.0);
    beaconLight.position.set(0, 15.8, 0);
    clockTower.add(beaconLight);

    const head = createSolidWithEdges(new THREE.BoxGeometry(3.0, 3.0, 3.0), solidBuildingMaterial, ctEdgeCyan);
    head.position.y = 17.1;
    clockTower.add(head);

    function createHolographicClockFace(isFront) {
      const faceGroup = new THREE.Group();

      const faceMesh = new THREE.Mesh(new THREE.PlaneGeometry(2.8, 2.8), hologramMaterial);
      faceMesh.position.set(0, 0, 0.02);
      faceGroup.add(faceMesh);

      const ticks = [];
      for (let d = 0; d < 12; d++) {
        const angle = (d / 12) * Math.PI * 2;
        const cos = Math.cos(angle);
        const sin = Math.sin(angle);
        ticks.push(cos * 0.82, sin * 0.82, 0.03, cos * 0.98, sin * 0.98, 0.03);
      }
      faceGroup.add(segmentsToLineSegments(ticks, ctEdgeAmber));

      const hrGroup = new THREE.Group();
      const hrLine = pointsToLine2([new THREE.Vector3(0, 0, 0.04), new THREE.Vector3(0, 0.52, 0.04)], ctEdgeAmber);
      hrGroup.add(hrLine);
      faceGroup.add(hrGroup);
      dynamicObjects.clockHands.push({ type: 'hour', mesh: hrGroup });

      const minGroup = new THREE.Group();
      const minLine = pointsToLine2([new THREE.Vector3(0, 0, 0.05), new THREE.Vector3(0, 0.8, 0.05)], ctEdgeCyan);
      minGroup.add(minLine);
      faceGroup.add(minGroup);
      dynamicObjects.clockHands.push({ type: 'minute', mesh: minGroup });

      const secGroup = new THREE.Group();
      const secLine = pointsToLine2([new THREE.Vector3(0, 0, 0.06), new THREE.Vector3(0, 0.9, 0.06)], ctEdgePink);
      secGroup.add(secLine);
      faceGroup.add(secGroup);
      dynamicObjects.clockHands.push({ type: 'second', mesh: secGroup });

      faceGroup.position.set(0, 17.1, isFront ? 1.52 : -1.52);
      if (!isFront) faceGroup.rotation.y = Math.PI;

      return faceGroup;
    }

    clockTower.add(createHolographicClockFace(true));  
    clockTower.add(createHolographicClockFace(false)); 

    const roofGeo = new THREE.ConeGeometry(2.1, 1.0, 4);
    roofGeo.rotateY(Math.PI / 4);
    const roof = createSolidWithEdges(roofGeo, solidBuildingMaterial, ctEdgePink);
    roof.position.y = 19.1;
    clockTower.add(roof);

    const needle = createSolidWithEdges(new THREE.BoxGeometry(0.12, 5.0, 0.12), solidBuildingMaterial, ctEdgePink);
    needle.position.y = 21.6;
    clockTower.add(needle);

    const r1 = edgesToLineSegments(new THREE.TorusGeometry(0.6, 0.03, 4, 16), ctEdgeCyan);
    r1.rotation.x = Math.PI / 2; r1.position.y = 20.0;
    const r2 = edgesToLineSegments(new THREE.TorusGeometry(0.4, 0.03, 4, 16), ctEdgeCyan);
    r2.rotation.x = Math.PI / 2; r2.position.y = 21.6;
    const r3 = edgesToLineSegments(new THREE.TorusGeometry(0.2, 0.03, 4, 16), ctEdgeCyan);
    r3.rotation.x = Math.PI / 2; r3.position.y = 23.2;
    clockTower.add(r1, r2, r3);

    const beaconPts = [new THREE.Vector3(0, 24.1, 0), new THREE.Vector3(0, 50.0, 0)];
    const beaconLine = pointsToLine2(beaconPts, makeLineMat('#00f0ff', 1.8, 0.65));
    clockTower.add(beaconLine);

    return clockTower;
  }

  function buildLandmarks() {
    const church = createChurchTemplate();
    const churchY = terrainHeight(landmarks.church.x, landmarks.church.z) - 0.4;
    church.position.set(landmarks.church.x, churchY, landmarks.church.z);
    church.lookAt(roadCurveX(landmarks.church.z), churchY, landmarks.church.z);
    church.rotation.y += Math.PI * 0.15;

    const churchInternalLight = new THREE.PointLight(0xff2a85, 3.0, 25.0, 1.8);
    churchInternalLight.position.set(0, 5.0, -1.0);
    church.add(churchInternalLight);

    const roseGlassLight = new THREE.PointLight(0x00f0ff, 2.0, 15.0, 2.0);
    roseGlassLight.position.set(0, 9.5, 7.5);
    church.add(roseGlassLight);

    const clockTower = createClockTowerTemplate();
    const ctY = terrainHeight(landmarks.clockTower.x, landmarks.clockTower.z) - 0.7;
    clockTower.position.set(landmarks.clockTower.x, ctY, landmarks.clockTower.z);
    clockTower.lookAt(roadCurveX(landmarks.clockTower.z), ctY, landmarks.clockTower.z);
    clockTower.rotation.y -= Math.PI * 0.12;

    const ctBaseLight = new THREE.PointLight(0xffb84a, 2.0, 12.0, 2.0);
    ctBaseLight.position.set(0, 1.5, 0);
    clockTower.add(ctBaseLight);

    villageGroup.add(church, clockTower);
  }

  function buildInstancedStructures() {
    const random = makeRandom(789);

    const residentialPlacements = [
      { z: -40, side: -1, scale: 1.1, offset: 10 },
      { z: -34, side: -1, scale: 0.9, offset: 9 },
      { z: -10, side: 1,  scale: 1.2, offset: 11 },
      { z: 0,   side: -1, scale: 1.0, offset: 9 },
      { z: 12,  side: 1,  scale: 1.0, offset: 10 },
      { z: 22,  side: 1,  scale: 1.1, offset: 10 },
      { z: 35,  side: -1, scale: 1.0, offset: 10 }
    ];

    const exclusionZones = [
      { x: landmarks.church.x, z: landmarks.church.z, radius: landmarks.church.radius },
      { x: landmarks.clockTower.x, z: landmarks.clockTower.z, radius: landmarks.clockTower.radius },
      { x: landmarks.billboard.x, z: landmarks.billboard.z, radius: landmarks.billboard.radius }
    ];

    const windmillsXZ = [
      { z: -45, side: -1, offset: 22 },
      { z: -15, side: 1, offset: 20 },
      { z: 30, side: -1, offset: 24 }
    ];
    for (const wm of windmillsXZ) {
      const wx = roadCurveX(wm.z) + wm.side * wm.offset;
      exclusionZones.push({ x: wx, z: wm.z, radius: 8.0 });
    }

    const baseBoxGeo = new THREE.BoxGeometry(3.6, 3.0, 3.6);
    const roofConeGeo = new THREE.ConeGeometry(2.8, 1.8, 4);
    roofConeGeo.rotateY(Math.PI / 4);

    const count = residentialPlacements.length;
    const instHutBase = new THREE.InstancedMesh(baseBoxGeo, instancedHutMaterial, count);
    const instHutRoof = new THREE.InstancedMesh(roofConeGeo, instancedHutMaterial, count);

    const flickerData = new Float32Array(count * 2);

    const tempMatrix = new THREE.Matrix4();
    const tempPos = new THREE.Vector3();
    const tempRot = new THREE.Quaternion();
    const tempScale = new THREE.Vector3();

    let instIndex = 0;
    const validHutPlacements = [];

    for (let i = 0; i < count; i++) {
      const item = residentialPlacements[i];
      const x = roadCurveX(item.z) + item.side * (item.offset + random() * 1.5);
      const y = terrainHeight(x, item.z);

      let collides = false;
      for (const zone of exclusionZones) {
        const dist = Math.sqrt(Math.pow(x - zone.x, 2) + Math.pow(item.z - zone.z, 2));
        if (dist < zone.radius) {
          collides = true;
          break;
        }
      }
      if (collides) continue;

      tempPos.set(x, y + 1.5 * item.scale, item.z);
      tempScale.setScalar(item.scale);
      
      const dummy = new THREE.Object3D();
      dummy.position.copy(tempPos);
      dummy.lookAt(roadCurveX(item.z), y + 1.5 * item.scale, item.z);
      dummy.rotation.y += (random() - 0.5) * 0.2;
      dummy.scale.copy(tempScale);
      dummy.updateMatrix();

      instHutBase.setMatrixAt(instIndex, dummy.matrix);

      dummy.position.y += 2.4 * item.scale;
      dummy.updateMatrix();
      instHutRoof.setMatrixAt(instIndex, dummy.matrix);

      flickerData[instIndex * 2] = random() * Math.PI * 2;
      flickerData[instIndex * 2 + 1] = 0.6 + random() * 1.8;

      validHutPlacements.push({ x, z: item.z, radius: 3.5 * item.scale });
      instIndex++;
    }

    baseBoxGeo.setAttribute('aFlickerParams', new THREE.InstancedBufferAttribute(flickerData, 2));
    roofConeGeo.setAttribute('aFlickerParams', new THREE.InstancedBufferAttribute(flickerData, 2));

    villageGroup.add(instHutBase, instHutRoof);

    const treeFoliageGeo = new THREE.ConeGeometry(1.5, 3.2, 5);
    const foliageInstCount = 38;
    const instFoliage = new THREE.InstancedMesh(treeFoliageGeo, instancedFoliageMaterial, foliageInstCount);

    const foliageFlicker = new Float32Array(foliageInstCount * 2);
    const foliageWind = new Float32Array(foliageInstCount * 2);

    let folIndex = 0;
    for (let i = 0; i < 150; i++) {
      if (folIndex >= foliageInstCount) break;

      const z = -47 + random() * 94;
      const x = -48 + random() * 96;

      if (Math.abs(x - roadCurveX(z)) < 9.0) continue;

      let collides = false;
      for (const zone of exclusionZones) {
        if (Math.sqrt(Math.pow(x - zone.x, 2) + Math.pow(z - zone.z, 2)) < zone.radius + 1.5) {
          collides = true;
          break;
        }
      }
      if (!collides) {
        for (const hut of validHutPlacements) {
          if (Math.sqrt(Math.pow(x - hut.x, 2) + Math.pow(z - hut.z, 2)) < hut.radius + 1.8) {
            collides = true;
            break;
          }
        }
      }
      if (collides) continue;

      const y = terrainHeight(x, z);
      const scale = 0.72 + random() * 0.65;

      tempPos.set(x, y + 1.6 * scale, z);
      tempScale.setScalar(scale);
      tempRot.setFromAxisAngle(new THREE.Vector3(0, 1, 0), random() * Math.PI * 2);

      tempMatrix.compose(tempPos, tempRot, tempScale);
      instFoliage.setMatrixAt(folIndex, tempMatrix);

      foliageWind[folIndex * 2] = random() * Math.PI * 2;
      foliageWind[folIndex * 2 + 1] = 0.4 + random() * 0.8;

      foliageFlicker[folIndex * 2] = random() * Math.PI * 2;
      foliageFlicker[folIndex * 2 + 1] = 0.8 + random() * 1.5;

      folIndex++;
    }

    treeFoliageGeo.setAttribute('aWindParams', new THREE.InstancedBufferAttribute(foliageWind, 2));
    treeFoliageGeo.setAttribute('aFlickerParams', new THREE.InstancedBufferAttribute(foliageFlicker, 2));

    villageGroup.add(instFoliage);
    dynamicObjects.instancedFoliage = instFoliage;

    buildWindmills();
    buildStreetLights();
  }

  function createWindmillTemplate() {
    const wmGroup = new THREE.Group();
    const neonCyan = makeLineMat('#00f0ff', 2.5, 1.0);
    const neonOrange = makeLineMat('#ff8a2a', 2.5, 1.0);
    const neonPink = makeLineMat('#ff2a85', 1.9, 0.76);

    const towerGeo = new THREE.CylinderGeometry(1.2, 2.5, 12.0, 6);
    const tower = createSolidWithEdges(towerGeo, solidBuildingMaterial, neonCyan);
    tower.position.y = 6.0;
    wmGroup.add(tower);

    const halo = edgesToLineSegments(new THREE.TorusGeometry(1.65, 0.08, 4, 32), neonPink);
    halo.position.y = 9.2;
    halo.rotation.x = Math.PI / 2;
    wmGroup.add(halo);

    const rotor = new THREE.Group();
    rotor.position.set(0, 11.0, 1.5);

    const hubGeo = new THREE.CylinderGeometry(0.6, 0.6, 1.2, 8);
    hubGeo.rotateX(Math.PI / 2);
    const hub = createSolidWithEdges(hubGeo, solidBuildingMaterial, neonOrange);
    rotor.add(hub);

    for (let i = 0; i < 4; i++) {
      const bladeGeo = new THREE.BoxGeometry(0.3, 5.5, 0.1);
      bladeGeo.translate(0, 3.0, 0);
      const blade = createSolidWithEdges(bladeGeo, solidBuildingMaterial, neonOrange);
      blade.rotation.z = (Math.PI / 2) * i;
      rotor.add(blade);
    }

    wmGroup.add(rotor);
    return { root: wmGroup, rotor };
  }

  function buildWindmills() {
    const wmConfig = [
      { z: -45, side: -1, offset: 22, rot: 0.5, speed: 1.2, phase: 0 },
      { z: -15, side: 1, offset: 20, rot: -0.3, speed: 0.85, phase: 1.5 },
      { z: 30, side: -1, offset: 24, rot: 0.8, speed: 1.0, phase: 3.14 }
    ];

    for (const item of wmConfig) {
      const x = roadCurveX(item.z) + item.side * item.offset;
      const y = terrainHeight(x, item.z);

      const wm = createWindmillTemplate();
      wm.root.position.set(x, y, item.z);
      wm.root.rotation.y = item.rot;
      villageGroup.add(wm.root);

      dynamicObjects.windmills.push({
        mesh: wm.rotor,
        speed: item.speed,
        phase: item.phase
      });
    }
  }

  function buildStreetLights() {
    const poleMat = createSolidMaterial(0x1a0c24, 0.9, 0.1, 0.48);
    const poleOutlineMat = makeLineMat('#a855f7', 1.8, 0.72);
    const glowTexture = createGlowTexture();

    const zs = [-40, -30, -20, -10, 0, 10, 20, 30, 40];

    for (let i = 0; i < zs.length; i++) {
      const z = zs[i];
      const side = i % 2 === 0 ? -1 : 1;
      const x = roadCurveX(z) + side * 4.0;
      const y = terrainHeight(x, z);

      const group = new THREE.Group();
      group.position.set(x, y, z);

      const pole = new THREE.Mesh(new THREE.CylinderGeometry(0.1, 0.15, 3.5, 6), poleMat);
      pole.position.y = 1.75;
      group.add(pole);

      const arm = new THREE.Mesh(new THREE.BoxGeometry(0.15, 0.15, 1.5), poleMat);
      arm.position.set(side * -0.6, 3.3, 0);
      arm.rotation.y = Math.PI / 2;
      group.add(arm);

      const poleOutline = edgesToLineSegments(new THREE.BoxGeometry(0.3, 3.5, 0.3), poleOutlineMat);
      poleOutline.position.y = 1.75;
      group.add(poleOutline);

      const lantern = new THREE.Mesh(new THREE.OctahedronGeometry(0.5, 0), lanternMaterial);
      lantern.position.set(side * -1.2, 3.0, 0);
      group.add(lantern);

      const point = new THREE.PointLight(0x00f0ff, 1.55, 15.0, 2.0);
      point.position.copy(lantern.position);
      group.add(point);
      lampLights.push(point);

      const spriteMat = new THREE.SpriteMaterial({
        map: glowTexture,
        color: 0x00f0ff,
        transparent: true,
        opacity: 0.76,
        blending: THREE.AdditiveBlending,
        depthWrite: false
      });

      const glow = new THREE.Sprite(spriteMat);
      glow.position.copy(lantern.position);
      glow.scale.set(5.0, 5.0, 1);
      group.add(glow);
      lampGlowSprites.push(glow);

      villageGroup.add(group);
    }
  }

  function buildNeonBillboard() {
    const group = new THREE.Group();

    const billboardHologramMat = buildHologramMaterial('#ff2a85');

    const panelFront = new THREE.Mesh(new THREE.PlaneGeometry(8.4, 3.15), billboardHologramMat);
    panelFront.position.set(0, 6.5, 0.15);
    group.add(panelFront);

    const panelBack = new THREE.Mesh(new THREE.PlaneGeometry(8.4, 3.15), billboardHologramMat);
    panelBack.position.set(0, 6.5, -0.15);
    panelBack.rotation.y = Math.PI;
    group.add(panelBack);

    dynamicObjects.billboardPanels.push(panelFront, panelBack);

    const frameMat = makeLineMat('#00f0ff', 3.2, 1.0);
    const framePink = makeLineMat('#ff2a85', 2.2, 0.82);

    const frame = edgesToLineSegments(new THREE.BoxGeometry(8.8, 3.55, 0.35), frameMat);
    frame.position.y = 6.5;
    group.add(frame);

    const backFrame = edgesToLineSegments(new THREE.BoxGeometry(9.4, 4.0, 0.6), framePink);
    backFrame.position.y = 6.5;
    group.add(backFrame);

    const poleMat = createSolidMaterial(0x080513, 0.9, 0.16, 0.55);
    const poleEdge = makeLineMat('#a855f7', 2.2, 0.8);

    const poleL = createSolidWithEdges(new THREE.BoxGeometry(0.22, 6.3, 0.22), poleMat, poleEdge);
    poleL.position.set(-3.65, 3.05, 0);
    group.add(poleL);

    const poleR = createSolidWithEdges(new THREE.BoxGeometry(0.22, 6.3, 0.22), poleMat, poleEdge);
    poleR.position.set(3.65, 3.05, 0);
    group.add(poleR);

    const baseBar = createSolidWithEdges(new THREE.BoxGeometry(8.0, 0.22, 0.4), poleMat, poleEdge);
    baseBar.position.set(0, 3.65, 0);
    group.add(baseBar);

    const glowTexture = createGlowTexture();
    const glowMat = new THREE.SpriteMaterial({
      map: glowTexture,
      color: 0xff2a85,
      transparent: true,
      opacity: 0.55,
      blending: THREE.AdditiveBlending,
      depthWrite: false
    });

    const glow = new THREE.Sprite(glowMat);
    glow.position.set(0, 6.5, 0);
    glow.scale.set(13, 6, 1);
    group.add(glow);

    const billboardLightA = new THREE.PointLight(0x00f0ff, 2.0, 22, 2.0);
    billboardLightA.position.set(-2.8, 6.6, 1.0);
    group.add(billboardLightA);

    const billboardLightB = new THREE.PointLight(0xff2a85, 2.0, 22, 2.0);
    billboardLightB.position.set(2.8, 6.6, -1.0);
    group.add(billboardLightB);

    dynamicObjects.billboardLights.push(billboardLightA, billboardLightB, glow);

    const y = terrainHeight(landmarks.billboard.x, landmarks.billboard.z);
    group.position.set(landmarks.billboard.x, y, landmarks.billboard.z);
    group.rotation.y = Math.PI / 5;
    group.scale.setScalar(1.6);

    villageGroup.add(group);
  }

  function buildAtmosphereSpecks() {
    const particleCount = 380;
    const geo = new THREE.BufferGeometry();
    const positions = new Float32Array(particleCount * 3);
    const phases = new Float32Array(particleCount);

    for (let i = 0; i < particleCount; i++) {
      const r = 30 + Math.random() * 65;
      const a = Math.random() * Math.PI * 2;
      positions[i * 3] = Math.cos(a) * r;
      positions[i * 3 + 1] = 6.0 + Math.random() * 24.0;
      positions[i * 3 + 2] = Math.sin(a) * r;
      phases[i] = Math.random() * Math.PI * 2;
    }

    geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
    geo.setAttribute('phase', new THREE.BufferAttribute(phases, 1));

    const mat = buildCurlNoiseSpecksMaterial();

    dynamicObjects.particles = new THREE.Points(geo, mat);
    villageGroup.add(dynamicObjects.particles);
  }

  function createHovercraftTemplate() {
    const hcGroup = new THREE.Group();

    const coreMat = createSolidMaterial(0x020508, 0.9, 0.18, 0.48);
    const edgeMat = makeLineMat('#ff2a85', 2.6, 1.0);
    const detailMat = makeLineMat('#00f0ff', 2.1, 1.0);
    const amberMat = makeLineMat('#ffb84a', 1.9, 0.9);

    const baseGeo = new THREE.CylinderGeometry(0.62, 0.9, 0.34, 8);
    baseGeo.scale(1.05, 1, 1.65);
    const base = createSolidWithEdges(baseGeo, coreMat, edgeMat);
    base.position.y = 0.15;
    hcGroup.add(base);

    const noseGeo = new THREE.ConeGeometry(0.72, 1.2, 4);
    noseGeo.rotateX(Math.PI / 2);
    const nose = createSolidWithEdges(noseGeo, coreMat, detailMat);
    nose.position.set(0, 0.34, 1.15);
    hcGroup.add(nose);

    const cabinGeo = new THREE.BoxGeometry(0.68, 0.42, 1.0);
    const cabin = createSolidWithEdges(cabinGeo, coreMat, detailMat);
    cabin.position.set(0, 0.58, 0.28);
    cabin.rotation.x = -0.08;
    hcGroup.add(cabin);

    const wingGeo = new THREE.BoxGeometry(2.25, 0.08, 0.42);
    const wing = createSolidWithEdges(wingGeo, coreMat, amberMat);
    wing.position.set(0, 0.28, -0.25);
    hcGroup.add(wing);

    const thrusterGeo = new THREE.CylinderGeometry(0.2, 0.16, 0.52, 8);
    thrusterGeo.rotateX(Math.PI / 2);

    const thrustL = createSolidWithEdges(thrusterGeo, coreMat, edgeMat);
    thrustL.position.set(-0.43, 0.42, -0.94);
    hcGroup.add(thrustL);

    const thrustR = createSolidWithEdges(thrusterGeo, coreMat, edgeMat);
    thrustR.position.set(0.43, 0.42, -0.94);
    hcGroup.add(thrustR);

    function addFlame(x) {
      const flameGroup = new THREE.Group();
      flameGroup.position.set(x, 0.42, -1.22);

      const planeGeo = new THREE.PlaneGeometry(0.75, 2.65, 1, 24);
      planeGeo.rotateX(-Math.PI / 2);
      planeGeo.translate(0, 0, -1.15);

      const flameA = new THREE.Mesh(planeGeo, flameMaterial);
      flameA.rotation.z = 0;
      flameGroup.add(flameA);

      const flameB = new THREE.Mesh(planeGeo, flameMaterial);
      flameB.rotation.z = Math.PI / 2;
      flameGroup.add(flameB);

      const fireGlowTex = createGlowTexture(128, "fire");
      const fireSprite = new THREE.Sprite(new THREE.SpriteMaterial({
        map: fireGlowTex,
        color: 0xff5a1c,
        transparent: true,
        opacity: 0.74,
        blending: THREE.AdditiveBlending,
        depthWrite: false
      }));
      fireSprite.position.set(0, 0, -1.1);
      fireSprite.scale.set(2.3, 1.15, 1);
      flameGroup.add(fireSprite);

      return flameGroup;
    }

    hcGroup.add(addFlame(-0.43));
    hcGroup.add(addFlame(0.43));

    const underLight = new THREE.PointLight(0xff2a85, 2.2, 8.0, 2.0);
    underLight.position.set(0, -0.25, 0);
    hcGroup.add(underLight);

    const fireLight = new THREE.PointLight(0xff6a22, 2.3, 10.0, 2.0);
    fireLight.position.set(0, 0.42, -2.0);
    hcGroup.add(fireLight);

    hcGroup.userData.fireLight = fireLight;
    return hcGroup;
  }

  function buildDrones() {
    const template = createHovercraftTemplate();

    for (let i = 0; i < 4; i++) {
      const drone = template.clone(true);
      drone.scale.setScalar(i === 0 ? 1.05 : 0.76);
      villageGroup.add(drone);

      dynamicObjects.drones.push({
        mesh: drone,
        offset: (i / 4) * Math.PI * 2,
        speed: 0.45 + Math.random() * 0.45,
        altitude: i === 0 ? 3.8 : 3.0 + Math.random() * 1.2
      });
    }
  }

  function createLopolyDragon(neonColorHex, bodyColorHex, wingMembraneColorHex) {
    const dragonGroup = new THREE.Group();

    const neonMat = makeLineMat(neonColorHex, 2.5, 1.0);
    const bodyMat = createSolidMaterial(bodyColorHex, 0.8, 0.2, 0.4);
    
    const wingMembraneMat = new THREE.MeshStandardMaterial({
      color: wingMembraneColorHex,
      metalness: 0.2,
      roughness: 0.8,
      transparent: true,
      opacity: 0.25,
      side: THREE.DoubleSide
    });

    const tailSegments = [];
    const neckSegments = [];
    const wings = { L: null, R: null };

    const torsoGeo = new THREE.BoxGeometry(1.5, 1.5, 4.0);
    const torso = createSolidWithEdges(torsoGeo, bodyMat, neonMat);
    dragonGroup.add(torso);

    let parentNode = torso;
    const neckCount = 3;
    for (let i = 0; i < neckCount; i++) {
      const pivot = new THREE.Group();
      if (i === 0) {
        pivot.position.set(0, 0.5, 1.8);
      } else {
        pivot.position.set(0, 0.4, 0.9);
      }
      
      const segGeo = new THREE.BoxGeometry(1.0 - i * 0.15, 1.0 - i * 0.15, 1.0);
      segGeo.translate(0, 0, 0.5); 
      const seg = createSolidWithEdges(segGeo, bodyMat, neonMat);
      pivot.add(seg);
      parentNode.add(pivot);
      neckSegments.push(pivot);
      parentNode = pivot;
    }

    const headGroup = new THREE.Group();
    headGroup.position.set(0, 0.3, 0.9);

    const skullGeo = new THREE.BoxGeometry(1.3, 1.1, 1.6);
    const skull = createSolidWithEdges(skullGeo, bodyMat, neonMat);
    skull.position.set(0, 0.2, 0.8);
    headGroup.add(skull);

    const snoutGeo = new THREE.ConeGeometry(0.65, 1.5, 5);
    snoutGeo.rotateX(Math.PI / 2);
    const snout = createSolidWithEdges(snoutGeo, bodyMat, neonMat);
    snout.position.set(0, -0.1, 2.1);
    headGroup.add(snout);

    const hornGeo = new THREE.ConeGeometry(0.18, 1.6, 4);
    hornGeo.rotateX(-Math.PI / 5);
    for (const side of [-1, 1]) {
      const horn = createSolidWithEdges(hornGeo, bodyMat, makeLineMat('#ffb84a', 2.0, 1.0));
      horn.position.set(side * 0.36, 0.8, 0.4);
      headGroup.add(horn);
    }

    const eyeGeo = new THREE.SphereGeometry(0.18, 4, 4);
    const eyeMat = new THREE.MeshBasicMaterial({ color: neonColorHex });
    for (const side of [-1, 1]) {
      const eye = new THREE.Mesh(eyeGeo, eyeMat);
      eye.position.set(side * 0.6, 0.35, 1.3);
      headGroup.add(eye);
    }

    parentNode.add(headGroup);

    parentNode = torso;
    const tailCount = 5;
    for (let i = 0; i < tailCount; i++) {
      const pivot = new THREE.Group();
      if (i === 0) {
        pivot.position.set(0, -0.2, -1.8);
      } else {
        pivot.position.set(0, 0, -0.9);
      }

      const segGeo = new THREE.BoxGeometry(0.9 - i * 0.12, 0.9 - i * 0.12, 1.0);
      segGeo.translate(0, 0, -0.5);
      const seg = createSolidWithEdges(segGeo, bodyMat, neonMat);
      pivot.add(seg);
      parentNode.add(pivot);
      tailSegments.push(pivot);
      parentNode = pivot;
    }

    const spadeGeo = new THREE.ConeGeometry(0.55, 1.5, 3);
    spadeGeo.rotateX(-Math.PI / 2);
    const spade = createSolidWithEdges(spadeGeo, bodyMat, makeLineMat('#ffe56b', 2.0, 1.0));
    spade.position.set(0, 0, -1.2);
    parentNode.add(spade);

    const wingLPivot = new THREE.Group();
    wingLPivot.position.set(-0.8, 0.6, 0.2);

    const armLGeo = new THREE.BoxGeometry(3.0, 0.2, 0.2);
    armLGeo.translate(-1.5, 0, 0);
    const armL = createSolidWithEdges(armLGeo, bodyMat, neonMat);
    wingLPivot.add(armL);

    const memLGeo = new THREE.ConeGeometry(1.5, 3.0, 3);
    memLGeo.rotateX(Math.PI / 2);
    memLGeo.scale(1.0, 0.05, 1.0);
    memLGeo.translate(-1.5, -0.8, -0.6);
    const memL = createSolidWithEdges(memLGeo, wingMembraneMat, neonMat);
    wingLPivot.add(memL);

    torso.add(wingLPivot);
    wings.L = wingLPivot;

    const wingRPivot = new THREE.Group();
    wingRPivot.position.set(0.8, 0.6, 0.2);

    const armRGeo = new THREE.BoxGeometry(3.0, 0.2, 0.2);
    armRGeo.translate(1.5, 0, 0);
    const armR = createSolidWithEdges(armRGeo, bodyMat, neonMat);
    wingRPivot.add(armR);

    const memRGeo = new THREE.ConeGeometry(1.5, 3.0, 3);
    memRGeo.rotateX(Math.PI / 2);
    memRGeo.scale(1.0, 0.05, 1.0);
    memRGeo.translate(1.5, -0.8, -0.6);
    const memR = createSolidWithEdges(memRGeo, wingMembraneMat, neonMat);
    wingRPivot.add(memR);

    torso.add(wingRPivot);
    wings.R = wingRPivot;

    const underGlowLight = new THREE.PointLight(neonColorHex, 2.5, 18.0, 1.8);
    underGlowLight.position.set(0, -1.5, 0);
    dragonGroup.add(underGlowLight);

    dragonGroup.userData = {
      wings,
      tailSegments,
      neckSegments,
      head: headGroup,
      glowLight: underGlowLight
    };

    return dragonGroup;
  }

  function buildDragons() {
    const parent1 = new THREE.Group();
    const model1 = createLopolyDragon('#00f0ff', '#050a18', '#004a63');
    model1.scale.setScalar(0.7);
    parent1.add(model1);
    villageGroup.add(parent1);

    dynamicObjects.dragons.push({
      parent: parent1,
      model: model1,
      type: 'ice',
      speedScale: 0.15,
      phaseOffset: 0
    });

    const parent2 = new THREE.Group();
    const model2 = createLopolyDragon('#ff2a85', '#120216', '#660233');
    model2.scale.setScalar(0.65);
    parent2.add(model2);
    villageGroup.add(parent2);

    dynamicObjects.dragons.push({
      parent: parent2,
      model: model2,
      type: 'fire',
      speedScale: 0.19,
      phaseOffset: Math.PI
    });
  }

  function getIcePath(time) {
    const x = Math.cos(time) * 44 + Math.sin(time * 2.0) * 6.0;
    const z = Math.sin(time) * 38;
    const y = 18 + Math.sin(time * 3.0) * 4.5 + terrainHeight(x, z) * 0.5;
    return new THREE.Vector3(x, y, z);
  }

  function getFirePath(time) {
    const x = Math.sin(time) * 36;
    const z = Math.sin(time * 2.0) * 26;
    const y = 22 + Math.cos(time) * 5.5 + terrainHeight(x, z) * 0.5;
    return new THREE.Vector3(x, y, z);
  }

  function animate() {
    requestAnimationFrame(animate);

    const delta = clock.getDelta();
    const elapsed = clock.getElapsedTime();
    const t = elapsed * state.rate;

    controls.target.x = Math.sin(elapsed * 0.1) * state.drift * 2.0;
    controls.target.z = Math.cos(elapsed * 0.08) * state.drift * 1.5;
    controls.update();

    for (const mat of neonMaterials) {
      if (mat.uniforms && mat.uniforms.time) {
        mat.uniforms.time.value = t;
      }
      if (mat.uniforms && mat.uniforms.neonPower) {
        mat.uniforms.neonPower.value = state.neon;
      }
    }

    for (const mat of flameMaterials) {
      if (mat.uniforms) {
        mat.uniforms.time.value = t;
        mat.uniforms.power.value = 0.85 + state.neon * 0.32;
      }
    }

    if (screenPass) {
      screenPass.uniforms.time.value = elapsed;
      screenPass.uniforms.drift.value = state.drift;
      screenPass.uniforms.neonPower.value = state.neon;
    }

    if (dynamicObjects.particles && dynamicObjects.particles.material.uniforms) {
      dynamicObjects.particles.material.uniforms.time.value = t;
      dynamicObjects.particles.material.uniforms.rate.value = state.rate;
      dynamicObjects.particles.material.uniforms.atmosphereIntensity.value = state.fog; 
    }

    if (instancedHutMaterial && instancedHutMaterial.uniforms) {
      instancedHutMaterial.uniforms.time.value = t;
      instancedHutMaterial.uniforms.rate.value = state.rate;
      instancedHutMaterial.uniforms.neonPower.value = state.neon;
    }

    if (instancedFoliageMaterial && instancedFoliageMaterial.uniforms) {
      instancedFoliageMaterial.uniforms.time.value = t;
      instancedFoliageMaterial.uniforms.rate.value = state.rate;
      instancedFoliageMaterial.uniforms.neonPower.value = state.neon;
    }

    const hourAngle = -t * 0.12;
    const minAngle = -t * 1.44;
    const secAngle = -t * 15.0;

    for (const hand of dynamicObjects.clockHands) {
      if (hand.type === 'hour') {
        hand.mesh.rotation.z = hourAngle;
      } else if (hand.type === 'minute') {
        hand.mesh.rotation.z = minAngle;
      } else if (hand.type === 'second') {
        hand.mesh.rotation.z = secAngle;
      }
    }

    const neonBoost = 0.55 + state.neon * 0.52;
    for (const mat of lineMaterials) {
      mat.opacity = mat.userData.baseOpacity * neonBoost;
      mat.linewidth = mat.userData.baseLinewidth * (0.84 + state.neon * 0.22);
    }

    for (let i = 0; i < lampLights.length; i++) {
      const flicker =
        0.84 +
        Math.sin(t * 4.0 + i) * 0.09 +
        Math.sin(t * 15.0 + i * 2.0) * 0.04;

      lampLights[i].intensity = (1.42 + i * 0.045) * flicker * state.neon;
      lampGlowSprites[i].material.opacity = 0.45 * flicker * state.neon;
      lampGlowSprites[i].scale.setScalar(4.25 + state.neon * 1.1);
    }

    for (const wm of dynamicObjects.windmills) {
      wm.mesh.rotation.z = -(t * wm.speed + wm.phase);
    }

    for (const dash of dynamicObjects.roadDashes) {
      const pulse = 0.78 + 0.22 * Math.sin(t * 4.0 + dash.phase);
      dash.mesh.scale.set(1, pulse, 1);
    }

    for (const obj of dynamicObjects.billboardLights) {
      if (obj.isPointLight) {
        obj.intensity = (1.65 + Math.sin(t * 3.4 + obj.position.x) * 0.25) * state.neon;
      } else if (obj.isSprite) {
        obj.material.opacity = 0.35 + 0.22 * Math.sin(t * 3.0);
        obj.scale.set(12.5 + Math.sin(t * 2.4) * 0.7, 5.7 + Math.cos(t * 2.0) * 0.3, 1);
      }
    }

    for (const drone of dynamicObjects.drones) {
      const patrolZ = Math.sin(t * drone.speed * 0.22 + drone.offset) * 38;
      const patrolX = roadCurveX(patrolZ);
      const patrolY = terrainHeight(patrolX, patrolZ) + drone.altitude + Math.sin(t * 2.2 + drone.offset) * 0.45;

      drone.mesh.position.set(patrolX, patrolY, patrolZ);

      const nextZ = Math.sin((t + 0.06) * drone.speed * 0.22 + drone.offset) * 38;
      const nextX = roadCurveX(nextZ);
      const angle = Math.atan2(nextX - patrolX, nextZ - patrolZ);

      drone.mesh.rotation.y = angle;
      drone.mesh.rotation.x = Math.sin(t * 3.0 + drone.offset) * 0.08;
      drone.mesh.rotation.z = Math.sin(t * 2.5 + drone.offset) * 0.16;

      const fireLight = drone.mesh.userData.fireLight;
      if (fireLight) {
        fireLight.intensity = (1.7 + Math.sin(t * 20.0 + drone.offset) * 0.45) * state.neon;
      }
    }

    for (const drag of dynamicObjects.dragons) {
      const dragTime = t * drag.speedScale + drag.phaseOffset;

      let p1, p2, p3;
      if (drag.type === 'ice') {
        p1 = getIcePath(dragTime);
        p2 = getIcePath(dragTime + 0.02);
        p3 = getIcePath(dragTime + 0.04);
      } else {
        p1 = getFirePath(dragTime);
        p2 = getFirePath(dragTime + 0.02);
        p3 = getFirePath(dragTime + 0.04);
      }

      drag.parent.position.copy(p1);
      drag.parent.lookAt(p2);

      const v1 = new THREE.Vector2(p2.x - p1.x, p2.z - p1.z).normalize();
      const v2 = new THREE.Vector2(p3.x - p2.x, p3.z - p2.z).normalize();
      const crossProduct = v1.x * v2.y - v1.y * v2.x;
      const targetBank = crossProduct * 45.0;
      drag.model.rotation.z = THREE.MathUtils.lerp(drag.model.rotation.z, targetBank, 0.08);

      const userData = drag.model.userData;

      const flapFrequency = 5.2;
      const flapMotion = Math.sin(t * flapFrequency + drag.phaseOffset * 2.5) * 0.58;
      if (userData.wings.L) userData.wings.L.rotation.z = flapMotion;
      if (userData.wings.R) userData.wings.R.rotation.z = -flapMotion;

      const tailFreq = 3.6;
      const tailAmp = 0.14;
      for (let i = 0; i < userData.tailSegments.length; i++) {
        userData.tailSegments[i].rotation.y = Math.sin(t * tailFreq - i * 0.46 + drag.phaseOffset) * tailAmp;
      }

      const neckFreq = 3.6;
      const neckAmp = 0.06;
      for (let i = 0; i < userData.neckSegments.length; i++) {
        userData.neckSegments[i].rotation.y = Math.sin(t * neckFreq + i * 0.35 + drag.phaseOffset) * -neckAmp;
      }

      if (userData.glowLight) {
        userData.glowLight.intensity = (2.2 + Math.sin(t * 8.0 + drag.phaseOffset) * 0.7) * state.neon;
      }
    }

    villageGroup.rotation.y = Math.sin(elapsed * 0.02) * 0.022 * state.drift;

    composer.render(delta);
  }

  function onResize() {
    camera.aspect = window.innerWidth / window.innerHeight;
    camera.updateProjectionMatrix();

    renderer.setSize(window.innerWidth, window.innerHeight);
    composer.setSize(window.innerWidth, window.innerHeight);

    if (bloomPass) {
      bloomPass.setSize(window.innerWidth, window.innerHeight);
    }

    for (const mat of lineMaterials) {
      mat.resolution.set(window.innerWidth, window.innerHeight);
    }
  }

  window.onload = function () {
    init();
  };
</script>"#
}
